.TH "SpaceGame Directory Reference" 3 "Version 0.1.0" "Engine" \" -*- nroff -*-
.ad l
.nh
.SH NAME
SpaceGame Directory Reference
.SH SYNOPSIS
.br
.PP
.SS "Files"

.in +1c
.ti -1c
.RI "file \fBengine\&.c\fP"
.br
.ti -1c
.RI "file \fBengine\&.h\fP"
.br
.ti -1c
.RI "file \fBengine_buffers\&.c\fP"
.br
.ti -1c
.RI "file \fBengine_buffers\&.h\fP"
.br
.ti -1c
.RI "file \fBengine_component_funcs\&.c\fP"
.br
.ti -1c
.RI "file \fBengine_components\&.c\fP"
.br
.ti -1c
.RI "file \fBengine_components\&.h\fP"
.br
.ti -1c
.RI "file \fBengine_defs\&.h\fP"
.br
.ti -1c
.RI "file \fBengine_entity\&.c\fP"
.br
.ti -1c
.RI "file \fBengine_entity\&.h\fP"
.br
.ti -1c
.RI "file \fBengine_renderer\&.c\fP"
.br
.ti -1c
.RI "file \fBengine_renderer\&.h\fP"
.br
.ti -1c
.RI "file \fBengine_shaders\&.c\fP"
.br
.ti -1c
.RI "file \fBengine_shaders\&.h\fP"
.br
.ti -1c
.RI "file \fBengine_textures\&.c\fP"
.br
.ti -1c
.RI "file \fBengine_textures\&.h\fP"
.br
.ti -1c
.RI "file \fBengine_utils\&.c\fP"
.br
.ti -1c
.RI "file \fBengine_utils\&.h\fP"
.br
.ti -1c
.RI "file \fBgame\&.c\fP"
.br
.ti -1c
.RI "file \fBglad\&.c\fP"
.br
.in -1c
