.TH "engine_entity" 3 "Version 0.1.0" "Engine" \" -*- nroff -*-
.ad l
.nh
.SH NAME
engine_entity \- An entity, contains position, size, texture, and component data\&.  

.SH SYNOPSIS
.br
.PP
.PP
\fR#include <engine_defs\&.h>\fP
.SS "Data Fields"

.in +1c
.ti -1c
.RI "float \fBx\fP"
.br
.ti -1c
.RI "float \fBy\fP"
.br
.ti -1c
.RI "float \fBwidth\fP"
.br
.ti -1c
.RI "float \fBheight\fP"
.br
.ti -1c
.RI "EngineEntityKey \fBkey\fP"
.br
.ti -1c
.RI "EngineTextureKey \fBtexkey\fP"
.br
.ti -1c
.RI "EngineComponent * \fBcomponents\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
An entity, contains position, size, texture, and component data\&. 
.PP
Definition at line \fB91\fP of file \fBengine_defs\&.h\fP\&.
.SH "Field Documentation"
.PP 
.SS "EngineComponent* components"

.PP
Definition at line \fB96\fP of file \fBengine_defs\&.h\fP\&.
.SS "float height"

.PP
Definition at line \fB93\fP of file \fBengine_defs\&.h\fP\&.
.SS "EngineEntityKey key"

.PP
Definition at line \fB94\fP of file \fBengine_defs\&.h\fP\&.
.SS "EngineTextureKey texkey"

.PP
Definition at line \fB95\fP of file \fBengine_defs\&.h\fP\&.
.SS "float width"

.PP
Definition at line \fB93\fP of file \fBengine_defs\&.h\fP\&.
.SS "float x"

.PP
Definition at line \fB92\fP of file \fBengine_defs\&.h\fP\&.
.SS "float y"

.PP
Definition at line \fB92\fP of file \fBengine_defs\&.h\fP\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Engine from the source code\&.
