.TH "SpaceGame/engine_renderer.c" 3 "Version 0.1.0" "Engine" \" -*- nroff -*-
.ad l
.nh
.SH NAME
SpaceGame/engine_renderer.c
.SH SYNOPSIS
.br
.PP
\fR#include 'engine_renderer\&.h'\fP
.br
\fR#include 'engine_buffers\&.h'\fP
.br
\fR#include 'engine_shaders\&.h'\fP
.br
\fR#include 'engine_textures\&.h'\fP
.br
\fR#include 'engine_entity\&.h'\fP
.br
\fR#include <cglm/cglm\&.h>\fP
.br

.SS "Functions"

.in +1c
.ti -1c
.RI "void \fBengineRenderEntity\fP (\fBEngineContext\fP *ctx, \fBEngineEntityKey\fP key)"
.br
.in -1c
.SH "Function Documentation"
.PP 
.SS "void engineRenderEntity (\fBEngineContext\fP * ctx, \fBEngineEntityKey\fP key)"

.PP
Definition at line \fB19\fP of file \fBengine_renderer\&.c\fP\&.
.SH "Author"
.PP 
Generated automatically by Doxygen for Engine from the source code\&.
