.TH "engine_component" 3 "Version 0.1.0" "Engine" \" -*- nroff -*-
.ad l
.nh
.SH NAME
engine_component \- A component used for the functionality of entities\&.  

.SH SYNOPSIS
.br
.PP
.PP
\fR#include <engine_defs\&.h>\fP
.SS "Data Fields"

.in +1c
.ti -1c
.RI "EngineComponentID \fBid\fP"
.br
.ti -1c
.RI "EngineComponentType \fBtype\fP"
.br
.ti -1c
.RI "EngineComponentFunc \fBfunc\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
A component used for the functionality of entities\&. 
.PP
Definition at line \fB102\fP of file \fBengine_defs\&.h\fP\&.
.SH "Field Documentation"
.PP 
.SS "EngineComponentFunc func"

.PP
Definition at line \fB105\fP of file \fBengine_defs\&.h\fP\&.
.SS "EngineComponentID id"

.PP
Definition at line \fB103\fP of file \fBengine_defs\&.h\fP\&.
.SS "EngineComponentType type"

.PP
Definition at line \fB104\fP of file \fBengine_defs\&.h\fP\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Engine from the source code\&.
