.TH "SpaceGame/glad.c" 3 "Version 0.1.0" "Engine" \" -*- nroff -*-
.ad l
.nh
.SH NAME
SpaceGame/glad.c
.SH SYNOPSIS
.br
.PP
\fR#include <stdio\&.h>\fP
.br
\fR#include <stdlib\&.h>\fP
.br
\fR#include <string\&.h>\fP
.br
\fR#include <glad/glad\&.h>\fP
.br
\fR#include <dlfcn\&.h>\fP
.br

.SS "Typedefs"

.in +1c
.ti -1c
.RI "typedef void *APIENTRYP \fBPFNGLXGETPROCADDRESSPROC_PRIVATE\fP(const char *)"
.br
.in -1c
.SS "Functions"

.in +1c
.ti -1c
.RI "int \fBgladLoadGL\fP (void)"
.br
.ti -1c
.RI "int \fBgladLoadGLLoader\fP (GLADloadproc load)"
.br
.in -1c
.SS "Variables"

.in +1c
.ti -1c
.RI "struct gladGLversionStruct \fBGLVersion\fP = { 0, 0 }"
.br
.ti -1c
.RI "int \fBGLAD_GL_VERSION_1_0\fP = 0"
.br
.ti -1c
.RI "int \fBGLAD_GL_VERSION_1_1\fP = 0"
.br
.ti -1c
.RI "int \fBGLAD_GL_VERSION_1_2\fP = 0"
.br
.ti -1c
.RI "int \fBGLAD_GL_VERSION_1_3\fP = 0"
.br
.ti -1c
.RI "int \fBGLAD_GL_VERSION_1_4\fP = 0"
.br
.ti -1c
.RI "int \fBGLAD_GL_VERSION_1_5\fP = 0"
.br
.ti -1c
.RI "int \fBGLAD_GL_VERSION_2_0\fP = 0"
.br
.ti -1c
.RI "int \fBGLAD_GL_VERSION_2_1\fP = 0"
.br
.ti -1c
.RI "int \fBGLAD_GL_VERSION_3_0\fP = 0"
.br
.ti -1c
.RI "int \fBGLAD_GL_VERSION_3_1\fP = 0"
.br
.ti -1c
.RI "int \fBGLAD_GL_VERSION_3_2\fP = 0"
.br
.ti -1c
.RI "int \fBGLAD_GL_VERSION_3_3\fP = 0"
.br
.ti -1c
.RI "PFNGLACTIVETEXTUREPROC \fBglad_glActiveTexture\fP = NULL"
.br
.ti -1c
.RI "PFNGLATTACHSHADERPROC \fBglad_glAttachShader\fP = NULL"
.br
.ti -1c
.RI "PFNGLBEGINCONDITIONALRENDERPROC \fBglad_glBeginConditionalRender\fP = NULL"
.br
.ti -1c
.RI "PFNGLBEGINQUERYPROC \fBglad_glBeginQuery\fP = NULL"
.br
.ti -1c
.RI "PFNGLBEGINTRANSFORMFEEDBACKPROC \fBglad_glBeginTransformFeedback\fP = NULL"
.br
.ti -1c
.RI "PFNGLBINDATTRIBLOCATIONPROC \fBglad_glBindAttribLocation\fP = NULL"
.br
.ti -1c
.RI "PFNGLBINDBUFFERPROC \fBglad_glBindBuffer\fP = NULL"
.br
.ti -1c
.RI "PFNGLBINDBUFFERBASEPROC \fBglad_glBindBufferBase\fP = NULL"
.br
.ti -1c
.RI "PFNGLBINDBUFFERRANGEPROC \fBglad_glBindBufferRange\fP = NULL"
.br
.ti -1c
.RI "PFNGLBINDFRAGDATALOCATIONPROC \fBglad_glBindFragDataLocation\fP = NULL"
.br
.ti -1c
.RI "PFNGLBINDFRAGDATALOCATIONINDEXEDPROC \fBglad_glBindFragDataLocationIndexed\fP = NULL"
.br
.ti -1c
.RI "PFNGLBINDFRAMEBUFFERPROC \fBglad_glBindFramebuffer\fP = NULL"
.br
.ti -1c
.RI "PFNGLBINDRENDERBUFFERPROC \fBglad_glBindRenderbuffer\fP = NULL"
.br
.ti -1c
.RI "PFNGLBINDSAMPLERPROC \fBglad_glBindSampler\fP = NULL"
.br
.ti -1c
.RI "PFNGLBINDTEXTUREPROC \fBglad_glBindTexture\fP = NULL"
.br
.ti -1c
.RI "PFNGLBINDVERTEXARRAYPROC \fBglad_glBindVertexArray\fP = NULL"
.br
.ti -1c
.RI "PFNGLBLENDCOLORPROC \fBglad_glBlendColor\fP = NULL"
.br
.ti -1c
.RI "PFNGLBLENDEQUATIONPROC \fBglad_glBlendEquation\fP = NULL"
.br
.ti -1c
.RI "PFNGLBLENDEQUATIONSEPARATEPROC \fBglad_glBlendEquationSeparate\fP = NULL"
.br
.ti -1c
.RI "PFNGLBLENDFUNCPROC \fBglad_glBlendFunc\fP = NULL"
.br
.ti -1c
.RI "PFNGLBLENDFUNCSEPARATEPROC \fBglad_glBlendFuncSeparate\fP = NULL"
.br
.ti -1c
.RI "PFNGLBLITFRAMEBUFFERPROC \fBglad_glBlitFramebuffer\fP = NULL"
.br
.ti -1c
.RI "PFNGLBUFFERDATAPROC \fBglad_glBufferData\fP = NULL"
.br
.ti -1c
.RI "PFNGLBUFFERSUBDATAPROC \fBglad_glBufferSubData\fP = NULL"
.br
.ti -1c
.RI "PFNGLCHECKFRAMEBUFFERSTATUSPROC \fBglad_glCheckFramebufferStatus\fP = NULL"
.br
.ti -1c
.RI "PFNGLCLAMPCOLORPROC \fBglad_glClampColor\fP = NULL"
.br
.ti -1c
.RI "PFNGLCLEARPROC \fBglad_glClear\fP = NULL"
.br
.ti -1c
.RI "PFNGLCLEARBUFFERFIPROC \fBglad_glClearBufferfi\fP = NULL"
.br
.ti -1c
.RI "PFNGLCLEARBUFFERFVPROC \fBglad_glClearBufferfv\fP = NULL"
.br
.ti -1c
.RI "PFNGLCLEARBUFFERIVPROC \fBglad_glClearBufferiv\fP = NULL"
.br
.ti -1c
.RI "PFNGLCLEARBUFFERUIVPROC \fBglad_glClearBufferuiv\fP = NULL"
.br
.ti -1c
.RI "PFNGLCLEARCOLORPROC \fBglad_glClearColor\fP = NULL"
.br
.ti -1c
.RI "PFNGLCLEARDEPTHPROC \fBglad_glClearDepth\fP = NULL"
.br
.ti -1c
.RI "PFNGLCLEARSTENCILPROC \fBglad_glClearStencil\fP = NULL"
.br
.ti -1c
.RI "PFNGLCLIENTWAITSYNCPROC \fBglad_glClientWaitSync\fP = NULL"
.br
.ti -1c
.RI "PFNGLCOLORMASKPROC \fBglad_glColorMask\fP = NULL"
.br
.ti -1c
.RI "PFNGLCOLORMASKIPROC \fBglad_glColorMaski\fP = NULL"
.br
.ti -1c
.RI "PFNGLCOLORP3UIPROC \fBglad_glColorP3ui\fP = NULL"
.br
.ti -1c
.RI "PFNGLCOLORP3UIVPROC \fBglad_glColorP3uiv\fP = NULL"
.br
.ti -1c
.RI "PFNGLCOLORP4UIPROC \fBglad_glColorP4ui\fP = NULL"
.br
.ti -1c
.RI "PFNGLCOLORP4UIVPROC \fBglad_glColorP4uiv\fP = NULL"
.br
.ti -1c
.RI "PFNGLCOMPILESHADERPROC \fBglad_glCompileShader\fP = NULL"
.br
.ti -1c
.RI "PFNGLCOMPRESSEDTEXIMAGE1DPROC \fBglad_glCompressedTexImage1D\fP = NULL"
.br
.ti -1c
.RI "PFNGLCOMPRESSEDTEXIMAGE2DPROC \fBglad_glCompressedTexImage2D\fP = NULL"
.br
.ti -1c
.RI "PFNGLCOMPRESSEDTEXIMAGE3DPROC \fBglad_glCompressedTexImage3D\fP = NULL"
.br
.ti -1c
.RI "PFNGLCOMPRESSEDTEXSUBIMAGE1DPROC \fBglad_glCompressedTexSubImage1D\fP = NULL"
.br
.ti -1c
.RI "PFNGLCOMPRESSEDTEXSUBIMAGE2DPROC \fBglad_glCompressedTexSubImage2D\fP = NULL"
.br
.ti -1c
.RI "PFNGLCOMPRESSEDTEXSUBIMAGE3DPROC \fBglad_glCompressedTexSubImage3D\fP = NULL"
.br
.ti -1c
.RI "PFNGLCOPYBUFFERSUBDATAPROC \fBglad_glCopyBufferSubData\fP = NULL"
.br
.ti -1c
.RI "PFNGLCOPYTEXIMAGE1DPROC \fBglad_glCopyTexImage1D\fP = NULL"
.br
.ti -1c
.RI "PFNGLCOPYTEXIMAGE2DPROC \fBglad_glCopyTexImage2D\fP = NULL"
.br
.ti -1c
.RI "PFNGLCOPYTEXSUBIMAGE1DPROC \fBglad_glCopyTexSubImage1D\fP = NULL"
.br
.ti -1c
.RI "PFNGLCOPYTEXSUBIMAGE2DPROC \fBglad_glCopyTexSubImage2D\fP = NULL"
.br
.ti -1c
.RI "PFNGLCOPYTEXSUBIMAGE3DPROC \fBglad_glCopyTexSubImage3D\fP = NULL"
.br
.ti -1c
.RI "PFNGLCREATEPROGRAMPROC \fBglad_glCreateProgram\fP = NULL"
.br
.ti -1c
.RI "PFNGLCREATESHADERPROC \fBglad_glCreateShader\fP = NULL"
.br
.ti -1c
.RI "PFNGLCULLFACEPROC \fBglad_glCullFace\fP = NULL"
.br
.ti -1c
.RI "PFNGLDELETEBUFFERSPROC \fBglad_glDeleteBuffers\fP = NULL"
.br
.ti -1c
.RI "PFNGLDELETEFRAMEBUFFERSPROC \fBglad_glDeleteFramebuffers\fP = NULL"
.br
.ti -1c
.RI "PFNGLDELETEPROGRAMPROC \fBglad_glDeleteProgram\fP = NULL"
.br
.ti -1c
.RI "PFNGLDELETEQUERIESPROC \fBglad_glDeleteQueries\fP = NULL"
.br
.ti -1c
.RI "PFNGLDELETERENDERBUFFERSPROC \fBglad_glDeleteRenderbuffers\fP = NULL"
.br
.ti -1c
.RI "PFNGLDELETESAMPLERSPROC \fBglad_glDeleteSamplers\fP = NULL"
.br
.ti -1c
.RI "PFNGLDELETESHADERPROC \fBglad_glDeleteShader\fP = NULL"
.br
.ti -1c
.RI "PFNGLDELETESYNCPROC \fBglad_glDeleteSync\fP = NULL"
.br
.ti -1c
.RI "PFNGLDELETETEXTURESPROC \fBglad_glDeleteTextures\fP = NULL"
.br
.ti -1c
.RI "PFNGLDELETEVERTEXARRAYSPROC \fBglad_glDeleteVertexArrays\fP = NULL"
.br
.ti -1c
.RI "PFNGLDEPTHFUNCPROC \fBglad_glDepthFunc\fP = NULL"
.br
.ti -1c
.RI "PFNGLDEPTHMASKPROC \fBglad_glDepthMask\fP = NULL"
.br
.ti -1c
.RI "PFNGLDEPTHRANGEPROC \fBglad_glDepthRange\fP = NULL"
.br
.ti -1c
.RI "PFNGLDETACHSHADERPROC \fBglad_glDetachShader\fP = NULL"
.br
.ti -1c
.RI "PFNGLDISABLEPROC \fBglad_glDisable\fP = NULL"
.br
.ti -1c
.RI "PFNGLDISABLEVERTEXATTRIBARRAYPROC \fBglad_glDisableVertexAttribArray\fP = NULL"
.br
.ti -1c
.RI "PFNGLDISABLEIPROC \fBglad_glDisablei\fP = NULL"
.br
.ti -1c
.RI "PFNGLDRAWARRAYSPROC \fBglad_glDrawArrays\fP = NULL"
.br
.ti -1c
.RI "PFNGLDRAWARRAYSINSTANCEDPROC \fBglad_glDrawArraysInstanced\fP = NULL"
.br
.ti -1c
.RI "PFNGLDRAWBUFFERPROC \fBglad_glDrawBuffer\fP = NULL"
.br
.ti -1c
.RI "PFNGLDRAWBUFFERSPROC \fBglad_glDrawBuffers\fP = NULL"
.br
.ti -1c
.RI "PFNGLDRAWELEMENTSPROC \fBglad_glDrawElements\fP = NULL"
.br
.ti -1c
.RI "PFNGLDRAWELEMENTSBASEVERTEXPROC \fBglad_glDrawElementsBaseVertex\fP = NULL"
.br
.ti -1c
.RI "PFNGLDRAWELEMENTSINSTANCEDPROC \fBglad_glDrawElementsInstanced\fP = NULL"
.br
.ti -1c
.RI "PFNGLDRAWELEMENTSINSTANCEDBASEVERTEXPROC \fBglad_glDrawElementsInstancedBaseVertex\fP = NULL"
.br
.ti -1c
.RI "PFNGLDRAWRANGEELEMENTSPROC \fBglad_glDrawRangeElements\fP = NULL"
.br
.ti -1c
.RI "PFNGLDRAWRANGEELEMENTSBASEVERTEXPROC \fBglad_glDrawRangeElementsBaseVertex\fP = NULL"
.br
.ti -1c
.RI "PFNGLENABLEPROC \fBglad_glEnable\fP = NULL"
.br
.ti -1c
.RI "PFNGLENABLEVERTEXATTRIBARRAYPROC \fBglad_glEnableVertexAttribArray\fP = NULL"
.br
.ti -1c
.RI "PFNGLENABLEIPROC \fBglad_glEnablei\fP = NULL"
.br
.ti -1c
.RI "PFNGLENDCONDITIONALRENDERPROC \fBglad_glEndConditionalRender\fP = NULL"
.br
.ti -1c
.RI "PFNGLENDQUERYPROC \fBglad_glEndQuery\fP = NULL"
.br
.ti -1c
.RI "PFNGLENDTRANSFORMFEEDBACKPROC \fBglad_glEndTransformFeedback\fP = NULL"
.br
.ti -1c
.RI "PFNGLFENCESYNCPROC \fBglad_glFenceSync\fP = NULL"
.br
.ti -1c
.RI "PFNGLFINISHPROC \fBglad_glFinish\fP = NULL"
.br
.ti -1c
.RI "PFNGLFLUSHPROC \fBglad_glFlush\fP = NULL"
.br
.ti -1c
.RI "PFNGLFLUSHMAPPEDBUFFERRANGEPROC \fBglad_glFlushMappedBufferRange\fP = NULL"
.br
.ti -1c
.RI "PFNGLFRAMEBUFFERRENDERBUFFERPROC \fBglad_glFramebufferRenderbuffer\fP = NULL"
.br
.ti -1c
.RI "PFNGLFRAMEBUFFERTEXTUREPROC \fBglad_glFramebufferTexture\fP = NULL"
.br
.ti -1c
.RI "PFNGLFRAMEBUFFERTEXTURE1DPROC \fBglad_glFramebufferTexture1D\fP = NULL"
.br
.ti -1c
.RI "PFNGLFRAMEBUFFERTEXTURE2DPROC \fBglad_glFramebufferTexture2D\fP = NULL"
.br
.ti -1c
.RI "PFNGLFRAMEBUFFERTEXTURE3DPROC \fBglad_glFramebufferTexture3D\fP = NULL"
.br
.ti -1c
.RI "PFNGLFRAMEBUFFERTEXTURELAYERPROC \fBglad_glFramebufferTextureLayer\fP = NULL"
.br
.ti -1c
.RI "PFNGLFRONTFACEPROC \fBglad_glFrontFace\fP = NULL"
.br
.ti -1c
.RI "PFNGLGENBUFFERSPROC \fBglad_glGenBuffers\fP = NULL"
.br
.ti -1c
.RI "PFNGLGENFRAMEBUFFERSPROC \fBglad_glGenFramebuffers\fP = NULL"
.br
.ti -1c
.RI "PFNGLGENQUERIESPROC \fBglad_glGenQueries\fP = NULL"
.br
.ti -1c
.RI "PFNGLGENRENDERBUFFERSPROC \fBglad_glGenRenderbuffers\fP = NULL"
.br
.ti -1c
.RI "PFNGLGENSAMPLERSPROC \fBglad_glGenSamplers\fP = NULL"
.br
.ti -1c
.RI "PFNGLGENTEXTURESPROC \fBglad_glGenTextures\fP = NULL"
.br
.ti -1c
.RI "PFNGLGENVERTEXARRAYSPROC \fBglad_glGenVertexArrays\fP = NULL"
.br
.ti -1c
.RI "PFNGLGENERATEMIPMAPPROC \fBglad_glGenerateMipmap\fP = NULL"
.br
.ti -1c
.RI "PFNGLGETACTIVEATTRIBPROC \fBglad_glGetActiveAttrib\fP = NULL"
.br
.ti -1c
.RI "PFNGLGETACTIVEUNIFORMPROC \fBglad_glGetActiveUniform\fP = NULL"
.br
.ti -1c
.RI "PFNGLGETACTIVEUNIFORMBLOCKNAMEPROC \fBglad_glGetActiveUniformBlockName\fP = NULL"
.br
.ti -1c
.RI "PFNGLGETACTIVEUNIFORMBLOCKIVPROC \fBglad_glGetActiveUniformBlockiv\fP = NULL"
.br
.ti -1c
.RI "PFNGLGETACTIVEUNIFORMNAMEPROC \fBglad_glGetActiveUniformName\fP = NULL"
.br
.ti -1c
.RI "PFNGLGETACTIVEUNIFORMSIVPROC \fBglad_glGetActiveUniformsiv\fP = NULL"
.br
.ti -1c
.RI "PFNGLGETATTACHEDSHADERSPROC \fBglad_glGetAttachedShaders\fP = NULL"
.br
.ti -1c
.RI "PFNGLGETATTRIBLOCATIONPROC \fBglad_glGetAttribLocation\fP = NULL"
.br
.ti -1c
.RI "PFNGLGETBOOLEANI_VPROC \fBglad_glGetBooleani_v\fP = NULL"
.br
.ti -1c
.RI "PFNGLGETBOOLEANVPROC \fBglad_glGetBooleanv\fP = NULL"
.br
.ti -1c
.RI "PFNGLGETBUFFERPARAMETERI64VPROC \fBglad_glGetBufferParameteri64v\fP = NULL"
.br
.ti -1c
.RI "PFNGLGETBUFFERPARAMETERIVPROC \fBglad_glGetBufferParameteriv\fP = NULL"
.br
.ti -1c
.RI "PFNGLGETBUFFERPOINTERVPROC \fBglad_glGetBufferPointerv\fP = NULL"
.br
.ti -1c
.RI "PFNGLGETBUFFERSUBDATAPROC \fBglad_glGetBufferSubData\fP = NULL"
.br
.ti -1c
.RI "PFNGLGETCOMPRESSEDTEXIMAGEPROC \fBglad_glGetCompressedTexImage\fP = NULL"
.br
.ti -1c
.RI "PFNGLGETDOUBLEVPROC \fBglad_glGetDoublev\fP = NULL"
.br
.ti -1c
.RI "PFNGLGETERRORPROC \fBglad_glGetError\fP = NULL"
.br
.ti -1c
.RI "PFNGLGETFLOATVPROC \fBglad_glGetFloatv\fP = NULL"
.br
.ti -1c
.RI "PFNGLGETFRAGDATAINDEXPROC \fBglad_glGetFragDataIndex\fP = NULL"
.br
.ti -1c
.RI "PFNGLGETFRAGDATALOCATIONPROC \fBglad_glGetFragDataLocation\fP = NULL"
.br
.ti -1c
.RI "PFNGLGETFRAMEBUFFERATTACHMENTPARAMETERIVPROC \fBglad_glGetFramebufferAttachmentParameteriv\fP = NULL"
.br
.ti -1c
.RI "PFNGLGETINTEGER64I_VPROC \fBglad_glGetInteger64i_v\fP = NULL"
.br
.ti -1c
.RI "PFNGLGETINTEGER64VPROC \fBglad_glGetInteger64v\fP = NULL"
.br
.ti -1c
.RI "PFNGLGETINTEGERI_VPROC \fBglad_glGetIntegeri_v\fP = NULL"
.br
.ti -1c
.RI "PFNGLGETINTEGERVPROC \fBglad_glGetIntegerv\fP = NULL"
.br
.ti -1c
.RI "PFNGLGETMULTISAMPLEFVPROC \fBglad_glGetMultisamplefv\fP = NULL"
.br
.ti -1c
.RI "PFNGLGETPROGRAMINFOLOGPROC \fBglad_glGetProgramInfoLog\fP = NULL"
.br
.ti -1c
.RI "PFNGLGETPROGRAMIVPROC \fBglad_glGetProgramiv\fP = NULL"
.br
.ti -1c
.RI "PFNGLGETQUERYOBJECTI64VPROC \fBglad_glGetQueryObjecti64v\fP = NULL"
.br
.ti -1c
.RI "PFNGLGETQUERYOBJECTIVPROC \fBglad_glGetQueryObjectiv\fP = NULL"
.br
.ti -1c
.RI "PFNGLGETQUERYOBJECTUI64VPROC \fBglad_glGetQueryObjectui64v\fP = NULL"
.br
.ti -1c
.RI "PFNGLGETQUERYOBJECTUIVPROC \fBglad_glGetQueryObjectuiv\fP = NULL"
.br
.ti -1c
.RI "PFNGLGETQUERYIVPROC \fBglad_glGetQueryiv\fP = NULL"
.br
.ti -1c
.RI "PFNGLGETRENDERBUFFERPARAMETERIVPROC \fBglad_glGetRenderbufferParameteriv\fP = NULL"
.br
.ti -1c
.RI "PFNGLGETSAMPLERPARAMETERIIVPROC \fBglad_glGetSamplerParameterIiv\fP = NULL"
.br
.ti -1c
.RI "PFNGLGETSAMPLERPARAMETERIUIVPROC \fBglad_glGetSamplerParameterIuiv\fP = NULL"
.br
.ti -1c
.RI "PFNGLGETSAMPLERPARAMETERFVPROC \fBglad_glGetSamplerParameterfv\fP = NULL"
.br
.ti -1c
.RI "PFNGLGETSAMPLERPARAMETERIVPROC \fBglad_glGetSamplerParameteriv\fP = NULL"
.br
.ti -1c
.RI "PFNGLGETSHADERINFOLOGPROC \fBglad_glGetShaderInfoLog\fP = NULL"
.br
.ti -1c
.RI "PFNGLGETSHADERSOURCEPROC \fBglad_glGetShaderSource\fP = NULL"
.br
.ti -1c
.RI "PFNGLGETSHADERIVPROC \fBglad_glGetShaderiv\fP = NULL"
.br
.ti -1c
.RI "PFNGLGETSTRINGPROC \fBglad_glGetString\fP = NULL"
.br
.ti -1c
.RI "PFNGLGETSTRINGIPROC \fBglad_glGetStringi\fP = NULL"
.br
.ti -1c
.RI "PFNGLGETSYNCIVPROC \fBglad_glGetSynciv\fP = NULL"
.br
.ti -1c
.RI "PFNGLGETTEXIMAGEPROC \fBglad_glGetTexImage\fP = NULL"
.br
.ti -1c
.RI "PFNGLGETTEXLEVELPARAMETERFVPROC \fBglad_glGetTexLevelParameterfv\fP = NULL"
.br
.ti -1c
.RI "PFNGLGETTEXLEVELPARAMETERIVPROC \fBglad_glGetTexLevelParameteriv\fP = NULL"
.br
.ti -1c
.RI "PFNGLGETTEXPARAMETERIIVPROC \fBglad_glGetTexParameterIiv\fP = NULL"
.br
.ti -1c
.RI "PFNGLGETTEXPARAMETERIUIVPROC \fBglad_glGetTexParameterIuiv\fP = NULL"
.br
.ti -1c
.RI "PFNGLGETTEXPARAMETERFVPROC \fBglad_glGetTexParameterfv\fP = NULL"
.br
.ti -1c
.RI "PFNGLGETTEXPARAMETERIVPROC \fBglad_glGetTexParameteriv\fP = NULL"
.br
.ti -1c
.RI "PFNGLGETTRANSFORMFEEDBACKVARYINGPROC \fBglad_glGetTransformFeedbackVarying\fP = NULL"
.br
.ti -1c
.RI "PFNGLGETUNIFORMBLOCKINDEXPROC \fBglad_glGetUniformBlockIndex\fP = NULL"
.br
.ti -1c
.RI "PFNGLGETUNIFORMINDICESPROC \fBglad_glGetUniformIndices\fP = NULL"
.br
.ti -1c
.RI "PFNGLGETUNIFORMLOCATIONPROC \fBglad_glGetUniformLocation\fP = NULL"
.br
.ti -1c
.RI "PFNGLGETUNIFORMFVPROC \fBglad_glGetUniformfv\fP = NULL"
.br
.ti -1c
.RI "PFNGLGETUNIFORMIVPROC \fBglad_glGetUniformiv\fP = NULL"
.br
.ti -1c
.RI "PFNGLGETUNIFORMUIVPROC \fBglad_glGetUniformuiv\fP = NULL"
.br
.ti -1c
.RI "PFNGLGETVERTEXATTRIBIIVPROC \fBglad_glGetVertexAttribIiv\fP = NULL"
.br
.ti -1c
.RI "PFNGLGETVERTEXATTRIBIUIVPROC \fBglad_glGetVertexAttribIuiv\fP = NULL"
.br
.ti -1c
.RI "PFNGLGETVERTEXATTRIBPOINTERVPROC \fBglad_glGetVertexAttribPointerv\fP = NULL"
.br
.ti -1c
.RI "PFNGLGETVERTEXATTRIBDVPROC \fBglad_glGetVertexAttribdv\fP = NULL"
.br
.ti -1c
.RI "PFNGLGETVERTEXATTRIBFVPROC \fBglad_glGetVertexAttribfv\fP = NULL"
.br
.ti -1c
.RI "PFNGLGETVERTEXATTRIBIVPROC \fBglad_glGetVertexAttribiv\fP = NULL"
.br
.ti -1c
.RI "PFNGLHINTPROC \fBglad_glHint\fP = NULL"
.br
.ti -1c
.RI "PFNGLISBUFFERPROC \fBglad_glIsBuffer\fP = NULL"
.br
.ti -1c
.RI "PFNGLISENABLEDPROC \fBglad_glIsEnabled\fP = NULL"
.br
.ti -1c
.RI "PFNGLISENABLEDIPROC \fBglad_glIsEnabledi\fP = NULL"
.br
.ti -1c
.RI "PFNGLISFRAMEBUFFERPROC \fBglad_glIsFramebuffer\fP = NULL"
.br
.ti -1c
.RI "PFNGLISPROGRAMPROC \fBglad_glIsProgram\fP = NULL"
.br
.ti -1c
.RI "PFNGLISQUERYPROC \fBglad_glIsQuery\fP = NULL"
.br
.ti -1c
.RI "PFNGLISRENDERBUFFERPROC \fBglad_glIsRenderbuffer\fP = NULL"
.br
.ti -1c
.RI "PFNGLISSAMPLERPROC \fBglad_glIsSampler\fP = NULL"
.br
.ti -1c
.RI "PFNGLISSHADERPROC \fBglad_glIsShader\fP = NULL"
.br
.ti -1c
.RI "PFNGLISSYNCPROC \fBglad_glIsSync\fP = NULL"
.br
.ti -1c
.RI "PFNGLISTEXTUREPROC \fBglad_glIsTexture\fP = NULL"
.br
.ti -1c
.RI "PFNGLISVERTEXARRAYPROC \fBglad_glIsVertexArray\fP = NULL"
.br
.ti -1c
.RI "PFNGLLINEWIDTHPROC \fBglad_glLineWidth\fP = NULL"
.br
.ti -1c
.RI "PFNGLLINKPROGRAMPROC \fBglad_glLinkProgram\fP = NULL"
.br
.ti -1c
.RI "PFNGLLOGICOPPROC \fBglad_glLogicOp\fP = NULL"
.br
.ti -1c
.RI "PFNGLMAPBUFFERPROC \fBglad_glMapBuffer\fP = NULL"
.br
.ti -1c
.RI "PFNGLMAPBUFFERRANGEPROC \fBglad_glMapBufferRange\fP = NULL"
.br
.ti -1c
.RI "PFNGLMULTIDRAWARRAYSPROC \fBglad_glMultiDrawArrays\fP = NULL"
.br
.ti -1c
.RI "PFNGLMULTIDRAWELEMENTSPROC \fBglad_glMultiDrawElements\fP = NULL"
.br
.ti -1c
.RI "PFNGLMULTIDRAWELEMENTSBASEVERTEXPROC \fBglad_glMultiDrawElementsBaseVertex\fP = NULL"
.br
.ti -1c
.RI "PFNGLMULTITEXCOORDP1UIPROC \fBglad_glMultiTexCoordP1ui\fP = NULL"
.br
.ti -1c
.RI "PFNGLMULTITEXCOORDP1UIVPROC \fBglad_glMultiTexCoordP1uiv\fP = NULL"
.br
.ti -1c
.RI "PFNGLMULTITEXCOORDP2UIPROC \fBglad_glMultiTexCoordP2ui\fP = NULL"
.br
.ti -1c
.RI "PFNGLMULTITEXCOORDP2UIVPROC \fBglad_glMultiTexCoordP2uiv\fP = NULL"
.br
.ti -1c
.RI "PFNGLMULTITEXCOORDP3UIPROC \fBglad_glMultiTexCoordP3ui\fP = NULL"
.br
.ti -1c
.RI "PFNGLMULTITEXCOORDP3UIVPROC \fBglad_glMultiTexCoordP3uiv\fP = NULL"
.br
.ti -1c
.RI "PFNGLMULTITEXCOORDP4UIPROC \fBglad_glMultiTexCoordP4ui\fP = NULL"
.br
.ti -1c
.RI "PFNGLMULTITEXCOORDP4UIVPROC \fBglad_glMultiTexCoordP4uiv\fP = NULL"
.br
.ti -1c
.RI "PFNGLNORMALP3UIPROC \fBglad_glNormalP3ui\fP = NULL"
.br
.ti -1c
.RI "PFNGLNORMALP3UIVPROC \fBglad_glNormalP3uiv\fP = NULL"
.br
.ti -1c
.RI "PFNGLPIXELSTOREFPROC \fBglad_glPixelStoref\fP = NULL"
.br
.ti -1c
.RI "PFNGLPIXELSTOREIPROC \fBglad_glPixelStorei\fP = NULL"
.br
.ti -1c
.RI "PFNGLPOINTPARAMETERFPROC \fBglad_glPointParameterf\fP = NULL"
.br
.ti -1c
.RI "PFNGLPOINTPARAMETERFVPROC \fBglad_glPointParameterfv\fP = NULL"
.br
.ti -1c
.RI "PFNGLPOINTPARAMETERIPROC \fBglad_glPointParameteri\fP = NULL"
.br
.ti -1c
.RI "PFNGLPOINTPARAMETERIVPROC \fBglad_glPointParameteriv\fP = NULL"
.br
.ti -1c
.RI "PFNGLPOINTSIZEPROC \fBglad_glPointSize\fP = NULL"
.br
.ti -1c
.RI "PFNGLPOLYGONMODEPROC \fBglad_glPolygonMode\fP = NULL"
.br
.ti -1c
.RI "PFNGLPOLYGONOFFSETPROC \fBglad_glPolygonOffset\fP = NULL"
.br
.ti -1c
.RI "PFNGLPRIMITIVERESTARTINDEXPROC \fBglad_glPrimitiveRestartIndex\fP = NULL"
.br
.ti -1c
.RI "PFNGLPROVOKINGVERTEXPROC \fBglad_glProvokingVertex\fP = NULL"
.br
.ti -1c
.RI "PFNGLQUERYCOUNTERPROC \fBglad_glQueryCounter\fP = NULL"
.br
.ti -1c
.RI "PFNGLREADBUFFERPROC \fBglad_glReadBuffer\fP = NULL"
.br
.ti -1c
.RI "PFNGLREADPIXELSPROC \fBglad_glReadPixels\fP = NULL"
.br
.ti -1c
.RI "PFNGLRENDERBUFFERSTORAGEPROC \fBglad_glRenderbufferStorage\fP = NULL"
.br
.ti -1c
.RI "PFNGLRENDERBUFFERSTORAGEMULTISAMPLEPROC \fBglad_glRenderbufferStorageMultisample\fP = NULL"
.br
.ti -1c
.RI "PFNGLSAMPLECOVERAGEPROC \fBglad_glSampleCoverage\fP = NULL"
.br
.ti -1c
.RI "PFNGLSAMPLEMASKIPROC \fBglad_glSampleMaski\fP = NULL"
.br
.ti -1c
.RI "PFNGLSAMPLERPARAMETERIIVPROC \fBglad_glSamplerParameterIiv\fP = NULL"
.br
.ti -1c
.RI "PFNGLSAMPLERPARAMETERIUIVPROC \fBglad_glSamplerParameterIuiv\fP = NULL"
.br
.ti -1c
.RI "PFNGLSAMPLERPARAMETERFPROC \fBglad_glSamplerParameterf\fP = NULL"
.br
.ti -1c
.RI "PFNGLSAMPLERPARAMETERFVPROC \fBglad_glSamplerParameterfv\fP = NULL"
.br
.ti -1c
.RI "PFNGLSAMPLERPARAMETERIPROC \fBglad_glSamplerParameteri\fP = NULL"
.br
.ti -1c
.RI "PFNGLSAMPLERPARAMETERIVPROC \fBglad_glSamplerParameteriv\fP = NULL"
.br
.ti -1c
.RI "PFNGLSCISSORPROC \fBglad_glScissor\fP = NULL"
.br
.ti -1c
.RI "PFNGLSECONDARYCOLORP3UIPROC \fBglad_glSecondaryColorP3ui\fP = NULL"
.br
.ti -1c
.RI "PFNGLSECONDARYCOLORP3UIVPROC \fBglad_glSecondaryColorP3uiv\fP = NULL"
.br
.ti -1c
.RI "PFNGLSHADERSOURCEPROC \fBglad_glShaderSource\fP = NULL"
.br
.ti -1c
.RI "PFNGLSTENCILFUNCPROC \fBglad_glStencilFunc\fP = NULL"
.br
.ti -1c
.RI "PFNGLSTENCILFUNCSEPARATEPROC \fBglad_glStencilFuncSeparate\fP = NULL"
.br
.ti -1c
.RI "PFNGLSTENCILMASKPROC \fBglad_glStencilMask\fP = NULL"
.br
.ti -1c
.RI "PFNGLSTENCILMASKSEPARATEPROC \fBglad_glStencilMaskSeparate\fP = NULL"
.br
.ti -1c
.RI "PFNGLSTENCILOPPROC \fBglad_glStencilOp\fP = NULL"
.br
.ti -1c
.RI "PFNGLSTENCILOPSEPARATEPROC \fBglad_glStencilOpSeparate\fP = NULL"
.br
.ti -1c
.RI "PFNGLTEXBUFFERPROC \fBglad_glTexBuffer\fP = NULL"
.br
.ti -1c
.RI "PFNGLTEXCOORDP1UIPROC \fBglad_glTexCoordP1ui\fP = NULL"
.br
.ti -1c
.RI "PFNGLTEXCOORDP1UIVPROC \fBglad_glTexCoordP1uiv\fP = NULL"
.br
.ti -1c
.RI "PFNGLTEXCOORDP2UIPROC \fBglad_glTexCoordP2ui\fP = NULL"
.br
.ti -1c
.RI "PFNGLTEXCOORDP2UIVPROC \fBglad_glTexCoordP2uiv\fP = NULL"
.br
.ti -1c
.RI "PFNGLTEXCOORDP3UIPROC \fBglad_glTexCoordP3ui\fP = NULL"
.br
.ti -1c
.RI "PFNGLTEXCOORDP3UIVPROC \fBglad_glTexCoordP3uiv\fP = NULL"
.br
.ti -1c
.RI "PFNGLTEXCOORDP4UIPROC \fBglad_glTexCoordP4ui\fP = NULL"
.br
.ti -1c
.RI "PFNGLTEXCOORDP4UIVPROC \fBglad_glTexCoordP4uiv\fP = NULL"
.br
.ti -1c
.RI "PFNGLTEXIMAGE1DPROC \fBglad_glTexImage1D\fP = NULL"
.br
.ti -1c
.RI "PFNGLTEXIMAGE2DPROC \fBglad_glTexImage2D\fP = NULL"
.br
.ti -1c
.RI "PFNGLTEXIMAGE2DMULTISAMPLEPROC \fBglad_glTexImage2DMultisample\fP = NULL"
.br
.ti -1c
.RI "PFNGLTEXIMAGE3DPROC \fBglad_glTexImage3D\fP = NULL"
.br
.ti -1c
.RI "PFNGLTEXIMAGE3DMULTISAMPLEPROC \fBglad_glTexImage3DMultisample\fP = NULL"
.br
.ti -1c
.RI "PFNGLTEXPARAMETERIIVPROC \fBglad_glTexParameterIiv\fP = NULL"
.br
.ti -1c
.RI "PFNGLTEXPARAMETERIUIVPROC \fBglad_glTexParameterIuiv\fP = NULL"
.br
.ti -1c
.RI "PFNGLTEXPARAMETERFPROC \fBglad_glTexParameterf\fP = NULL"
.br
.ti -1c
.RI "PFNGLTEXPARAMETERFVPROC \fBglad_glTexParameterfv\fP = NULL"
.br
.ti -1c
.RI "PFNGLTEXPARAMETERIPROC \fBglad_glTexParameteri\fP = NULL"
.br
.ti -1c
.RI "PFNGLTEXPARAMETERIVPROC \fBglad_glTexParameteriv\fP = NULL"
.br
.ti -1c
.RI "PFNGLTEXSUBIMAGE1DPROC \fBglad_glTexSubImage1D\fP = NULL"
.br
.ti -1c
.RI "PFNGLTEXSUBIMAGE2DPROC \fBglad_glTexSubImage2D\fP = NULL"
.br
.ti -1c
.RI "PFNGLTEXSUBIMAGE3DPROC \fBglad_glTexSubImage3D\fP = NULL"
.br
.ti -1c
.RI "PFNGLTRANSFORMFEEDBACKVARYINGSPROC \fBglad_glTransformFeedbackVaryings\fP = NULL"
.br
.ti -1c
.RI "PFNGLUNIFORM1FPROC \fBglad_glUniform1f\fP = NULL"
.br
.ti -1c
.RI "PFNGLUNIFORM1FVPROC \fBglad_glUniform1fv\fP = NULL"
.br
.ti -1c
.RI "PFNGLUNIFORM1IPROC \fBglad_glUniform1i\fP = NULL"
.br
.ti -1c
.RI "PFNGLUNIFORM1IVPROC \fBglad_glUniform1iv\fP = NULL"
.br
.ti -1c
.RI "PFNGLUNIFORM1UIPROC \fBglad_glUniform1ui\fP = NULL"
.br
.ti -1c
.RI "PFNGLUNIFORM1UIVPROC \fBglad_glUniform1uiv\fP = NULL"
.br
.ti -1c
.RI "PFNGLUNIFORM2FPROC \fBglad_glUniform2f\fP = NULL"
.br
.ti -1c
.RI "PFNGLUNIFORM2FVPROC \fBglad_glUniform2fv\fP = NULL"
.br
.ti -1c
.RI "PFNGLUNIFORM2IPROC \fBglad_glUniform2i\fP = NULL"
.br
.ti -1c
.RI "PFNGLUNIFORM2IVPROC \fBglad_glUniform2iv\fP = NULL"
.br
.ti -1c
.RI "PFNGLUNIFORM2UIPROC \fBglad_glUniform2ui\fP = NULL"
.br
.ti -1c
.RI "PFNGLUNIFORM2UIVPROC \fBglad_glUniform2uiv\fP = NULL"
.br
.ti -1c
.RI "PFNGLUNIFORM3FPROC \fBglad_glUniform3f\fP = NULL"
.br
.ti -1c
.RI "PFNGLUNIFORM3FVPROC \fBglad_glUniform3fv\fP = NULL"
.br
.ti -1c
.RI "PFNGLUNIFORM3IPROC \fBglad_glUniform3i\fP = NULL"
.br
.ti -1c
.RI "PFNGLUNIFORM3IVPROC \fBglad_glUniform3iv\fP = NULL"
.br
.ti -1c
.RI "PFNGLUNIFORM3UIPROC \fBglad_glUniform3ui\fP = NULL"
.br
.ti -1c
.RI "PFNGLUNIFORM3UIVPROC \fBglad_glUniform3uiv\fP = NULL"
.br
.ti -1c
.RI "PFNGLUNIFORM4FPROC \fBglad_glUniform4f\fP = NULL"
.br
.ti -1c
.RI "PFNGLUNIFORM4FVPROC \fBglad_glUniform4fv\fP = NULL"
.br
.ti -1c
.RI "PFNGLUNIFORM4IPROC \fBglad_glUniform4i\fP = NULL"
.br
.ti -1c
.RI "PFNGLUNIFORM4IVPROC \fBglad_glUniform4iv\fP = NULL"
.br
.ti -1c
.RI "PFNGLUNIFORM4UIPROC \fBglad_glUniform4ui\fP = NULL"
.br
.ti -1c
.RI "PFNGLUNIFORM4UIVPROC \fBglad_glUniform4uiv\fP = NULL"
.br
.ti -1c
.RI "PFNGLUNIFORMBLOCKBINDINGPROC \fBglad_glUniformBlockBinding\fP = NULL"
.br
.ti -1c
.RI "PFNGLUNIFORMMATRIX2FVPROC \fBglad_glUniformMatrix2fv\fP = NULL"
.br
.ti -1c
.RI "PFNGLUNIFORMMATRIX2X3FVPROC \fBglad_glUniformMatrix2x3fv\fP = NULL"
.br
.ti -1c
.RI "PFNGLUNIFORMMATRIX2X4FVPROC \fBglad_glUniformMatrix2x4fv\fP = NULL"
.br
.ti -1c
.RI "PFNGLUNIFORMMATRIX3FVPROC \fBglad_glUniformMatrix3fv\fP = NULL"
.br
.ti -1c
.RI "PFNGLUNIFORMMATRIX3X2FVPROC \fBglad_glUniformMatrix3x2fv\fP = NULL"
.br
.ti -1c
.RI "PFNGLUNIFORMMATRIX3X4FVPROC \fBglad_glUniformMatrix3x4fv\fP = NULL"
.br
.ti -1c
.RI "PFNGLUNIFORMMATRIX4FVPROC \fBglad_glUniformMatrix4fv\fP = NULL"
.br
.ti -1c
.RI "PFNGLUNIFORMMATRIX4X2FVPROC \fBglad_glUniformMatrix4x2fv\fP = NULL"
.br
.ti -1c
.RI "PFNGLUNIFORMMATRIX4X3FVPROC \fBglad_glUniformMatrix4x3fv\fP = NULL"
.br
.ti -1c
.RI "PFNGLUNMAPBUFFERPROC \fBglad_glUnmapBuffer\fP = NULL"
.br
.ti -1c
.RI "PFNGLUSEPROGRAMPROC \fBglad_glUseProgram\fP = NULL"
.br
.ti -1c
.RI "PFNGLVALIDATEPROGRAMPROC \fBglad_glValidateProgram\fP = NULL"
.br
.ti -1c
.RI "PFNGLVERTEXATTRIB1DPROC \fBglad_glVertexAttrib1d\fP = NULL"
.br
.ti -1c
.RI "PFNGLVERTEXATTRIB1DVPROC \fBglad_glVertexAttrib1dv\fP = NULL"
.br
.ti -1c
.RI "PFNGLVERTEXATTRIB1FPROC \fBglad_glVertexAttrib1f\fP = NULL"
.br
.ti -1c
.RI "PFNGLVERTEXATTRIB1FVPROC \fBglad_glVertexAttrib1fv\fP = NULL"
.br
.ti -1c
.RI "PFNGLVERTEXATTRIB1SPROC \fBglad_glVertexAttrib1s\fP = NULL"
.br
.ti -1c
.RI "PFNGLVERTEXATTRIB1SVPROC \fBglad_glVertexAttrib1sv\fP = NULL"
.br
.ti -1c
.RI "PFNGLVERTEXATTRIB2DPROC \fBglad_glVertexAttrib2d\fP = NULL"
.br
.ti -1c
.RI "PFNGLVERTEXATTRIB2DVPROC \fBglad_glVertexAttrib2dv\fP = NULL"
.br
.ti -1c
.RI "PFNGLVERTEXATTRIB2FPROC \fBglad_glVertexAttrib2f\fP = NULL"
.br
.ti -1c
.RI "PFNGLVERTEXATTRIB2FVPROC \fBglad_glVertexAttrib2fv\fP = NULL"
.br
.ti -1c
.RI "PFNGLVERTEXATTRIB2SPROC \fBglad_glVertexAttrib2s\fP = NULL"
.br
.ti -1c
.RI "PFNGLVERTEXATTRIB2SVPROC \fBglad_glVertexAttrib2sv\fP = NULL"
.br
.ti -1c
.RI "PFNGLVERTEXATTRIB3DPROC \fBglad_glVertexAttrib3d\fP = NULL"
.br
.ti -1c
.RI "PFNGLVERTEXATTRIB3DVPROC \fBglad_glVertexAttrib3dv\fP = NULL"
.br
.ti -1c
.RI "PFNGLVERTEXATTRIB3FPROC \fBglad_glVertexAttrib3f\fP = NULL"
.br
.ti -1c
.RI "PFNGLVERTEXATTRIB3FVPROC \fBglad_glVertexAttrib3fv\fP = NULL"
.br
.ti -1c
.RI "PFNGLVERTEXATTRIB3SPROC \fBglad_glVertexAttrib3s\fP = NULL"
.br
.ti -1c
.RI "PFNGLVERTEXATTRIB3SVPROC \fBglad_glVertexAttrib3sv\fP = NULL"
.br
.ti -1c
.RI "PFNGLVERTEXATTRIB4NBVPROC \fBglad_glVertexAttrib4Nbv\fP = NULL"
.br
.ti -1c
.RI "PFNGLVERTEXATTRIB4NIVPROC \fBglad_glVertexAttrib4Niv\fP = NULL"
.br
.ti -1c
.RI "PFNGLVERTEXATTRIB4NSVPROC \fBglad_glVertexAttrib4Nsv\fP = NULL"
.br
.ti -1c
.RI "PFNGLVERTEXATTRIB4NUBPROC \fBglad_glVertexAttrib4Nub\fP = NULL"
.br
.ti -1c
.RI "PFNGLVERTEXATTRIB4NUBVPROC \fBglad_glVertexAttrib4Nubv\fP = NULL"
.br
.ti -1c
.RI "PFNGLVERTEXATTRIB4NUIVPROC \fBglad_glVertexAttrib4Nuiv\fP = NULL"
.br
.ti -1c
.RI "PFNGLVERTEXATTRIB4NUSVPROC \fBglad_glVertexAttrib4Nusv\fP = NULL"
.br
.ti -1c
.RI "PFNGLVERTEXATTRIB4BVPROC \fBglad_glVertexAttrib4bv\fP = NULL"
.br
.ti -1c
.RI "PFNGLVERTEXATTRIB4DPROC \fBglad_glVertexAttrib4d\fP = NULL"
.br
.ti -1c
.RI "PFNGLVERTEXATTRIB4DVPROC \fBglad_glVertexAttrib4dv\fP = NULL"
.br
.ti -1c
.RI "PFNGLVERTEXATTRIB4FPROC \fBglad_glVertexAttrib4f\fP = NULL"
.br
.ti -1c
.RI "PFNGLVERTEXATTRIB4FVPROC \fBglad_glVertexAttrib4fv\fP = NULL"
.br
.ti -1c
.RI "PFNGLVERTEXATTRIB4IVPROC \fBglad_glVertexAttrib4iv\fP = NULL"
.br
.ti -1c
.RI "PFNGLVERTEXATTRIB4SPROC \fBglad_glVertexAttrib4s\fP = NULL"
.br
.ti -1c
.RI "PFNGLVERTEXATTRIB4SVPROC \fBglad_glVertexAttrib4sv\fP = NULL"
.br
.ti -1c
.RI "PFNGLVERTEXATTRIB4UBVPROC \fBglad_glVertexAttrib4ubv\fP = NULL"
.br
.ti -1c
.RI "PFNGLVERTEXATTRIB4UIVPROC \fBglad_glVertexAttrib4uiv\fP = NULL"
.br
.ti -1c
.RI "PFNGLVERTEXATTRIB4USVPROC \fBglad_glVertexAttrib4usv\fP = NULL"
.br
.ti -1c
.RI "PFNGLVERTEXATTRIBDIVISORPROC \fBglad_glVertexAttribDivisor\fP = NULL"
.br
.ti -1c
.RI "PFNGLVERTEXATTRIBI1IPROC \fBglad_glVertexAttribI1i\fP = NULL"
.br
.ti -1c
.RI "PFNGLVERTEXATTRIBI1IVPROC \fBglad_glVertexAttribI1iv\fP = NULL"
.br
.ti -1c
.RI "PFNGLVERTEXATTRIBI1UIPROC \fBglad_glVertexAttribI1ui\fP = NULL"
.br
.ti -1c
.RI "PFNGLVERTEXATTRIBI1UIVPROC \fBglad_glVertexAttribI1uiv\fP = NULL"
.br
.ti -1c
.RI "PFNGLVERTEXATTRIBI2IPROC \fBglad_glVertexAttribI2i\fP = NULL"
.br
.ti -1c
.RI "PFNGLVERTEXATTRIBI2IVPROC \fBglad_glVertexAttribI2iv\fP = NULL"
.br
.ti -1c
.RI "PFNGLVERTEXATTRIBI2UIPROC \fBglad_glVertexAttribI2ui\fP = NULL"
.br
.ti -1c
.RI "PFNGLVERTEXATTRIBI2UIVPROC \fBglad_glVertexAttribI2uiv\fP = NULL"
.br
.ti -1c
.RI "PFNGLVERTEXATTRIBI3IPROC \fBglad_glVertexAttribI3i\fP = NULL"
.br
.ti -1c
.RI "PFNGLVERTEXATTRIBI3IVPROC \fBglad_glVertexAttribI3iv\fP = NULL"
.br
.ti -1c
.RI "PFNGLVERTEXATTRIBI3UIPROC \fBglad_glVertexAttribI3ui\fP = NULL"
.br
.ti -1c
.RI "PFNGLVERTEXATTRIBI3UIVPROC \fBglad_glVertexAttribI3uiv\fP = NULL"
.br
.ti -1c
.RI "PFNGLVERTEXATTRIBI4BVPROC \fBglad_glVertexAttribI4bv\fP = NULL"
.br
.ti -1c
.RI "PFNGLVERTEXATTRIBI4IPROC \fBglad_glVertexAttribI4i\fP = NULL"
.br
.ti -1c
.RI "PFNGLVERTEXATTRIBI4IVPROC \fBglad_glVertexAttribI4iv\fP = NULL"
.br
.ti -1c
.RI "PFNGLVERTEXATTRIBI4SVPROC \fBglad_glVertexAttribI4sv\fP = NULL"
.br
.ti -1c
.RI "PFNGLVERTEXATTRIBI4UBVPROC \fBglad_glVertexAttribI4ubv\fP = NULL"
.br
.ti -1c
.RI "PFNGLVERTEXATTRIBI4UIPROC \fBglad_glVertexAttribI4ui\fP = NULL"
.br
.ti -1c
.RI "PFNGLVERTEXATTRIBI4UIVPROC \fBglad_glVertexAttribI4uiv\fP = NULL"
.br
.ti -1c
.RI "PFNGLVERTEXATTRIBI4USVPROC \fBglad_glVertexAttribI4usv\fP = NULL"
.br
.ti -1c
.RI "PFNGLVERTEXATTRIBIPOINTERPROC \fBglad_glVertexAttribIPointer\fP = NULL"
.br
.ti -1c
.RI "PFNGLVERTEXATTRIBP1UIPROC \fBglad_glVertexAttribP1ui\fP = NULL"
.br
.ti -1c
.RI "PFNGLVERTEXATTRIBP1UIVPROC \fBglad_glVertexAttribP1uiv\fP = NULL"
.br
.ti -1c
.RI "PFNGLVERTEXATTRIBP2UIPROC \fBglad_glVertexAttribP2ui\fP = NULL"
.br
.ti -1c
.RI "PFNGLVERTEXATTRIBP2UIVPROC \fBglad_glVertexAttribP2uiv\fP = NULL"
.br
.ti -1c
.RI "PFNGLVERTEXATTRIBP3UIPROC \fBglad_glVertexAttribP3ui\fP = NULL"
.br
.ti -1c
.RI "PFNGLVERTEXATTRIBP3UIVPROC \fBglad_glVertexAttribP3uiv\fP = NULL"
.br
.ti -1c
.RI "PFNGLVERTEXATTRIBP4UIPROC \fBglad_glVertexAttribP4ui\fP = NULL"
.br
.ti -1c
.RI "PFNGLVERTEXATTRIBP4UIVPROC \fBglad_glVertexAttribP4uiv\fP = NULL"
.br
.ti -1c
.RI "PFNGLVERTEXATTRIBPOINTERPROC \fBglad_glVertexAttribPointer\fP = NULL"
.br
.ti -1c
.RI "PFNGLVERTEXP2UIPROC \fBglad_glVertexP2ui\fP = NULL"
.br
.ti -1c
.RI "PFNGLVERTEXP2UIVPROC \fBglad_glVertexP2uiv\fP = NULL"
.br
.ti -1c
.RI "PFNGLVERTEXP3UIPROC \fBglad_glVertexP3ui\fP = NULL"
.br
.ti -1c
.RI "PFNGLVERTEXP3UIVPROC \fBglad_glVertexP3uiv\fP = NULL"
.br
.ti -1c
.RI "PFNGLVERTEXP4UIPROC \fBglad_glVertexP4ui\fP = NULL"
.br
.ti -1c
.RI "PFNGLVERTEXP4UIVPROC \fBglad_glVertexP4uiv\fP = NULL"
.br
.ti -1c
.RI "PFNGLVIEWPORTPROC \fBglad_glViewport\fP = NULL"
.br
.ti -1c
.RI "PFNGLWAITSYNCPROC \fBglad_glWaitSync\fP = NULL"
.br
.in -1c
.SH "Typedef Documentation"
.PP 
.SS "typedef void *APIENTRYP PFNGLXGETPROCADDRESSPROC_PRIVATE(const char *)"

.PP
Definition at line \fB83\fP of file \fBglad\&.c\fP\&.
.SH "Function Documentation"
.PP 
.SS "int gladLoadGL (void )"

.PP
Definition at line \fB148\fP of file \fBglad\&.c\fP\&.
.SS "int gladLoadGLLoader (GLADloadproc load)"

.PP
Definition at line \fB1118\fP of file \fBglad\&.c\fP\&.
.SH "Variable Documentation"
.PP 
.SS "int GLAD_GL_VERSION_1_0 = 0"

.PP
Definition at line \fB258\fP of file \fBglad\&.c\fP\&.
.SS "int GLAD_GL_VERSION_1_1 = 0"

.PP
Definition at line \fB259\fP of file \fBglad\&.c\fP\&.
.SS "int GLAD_GL_VERSION_1_2 = 0"

.PP
Definition at line \fB260\fP of file \fBglad\&.c\fP\&.
.SS "int GLAD_GL_VERSION_1_3 = 0"

.PP
Definition at line \fB261\fP of file \fBglad\&.c\fP\&.
.SS "int GLAD_GL_VERSION_1_4 = 0"

.PP
Definition at line \fB262\fP of file \fBglad\&.c\fP\&.
.SS "int GLAD_GL_VERSION_1_5 = 0"

.PP
Definition at line \fB263\fP of file \fBglad\&.c\fP\&.
.SS "int GLAD_GL_VERSION_2_0 = 0"

.PP
Definition at line \fB264\fP of file \fBglad\&.c\fP\&.
.SS "int GLAD_GL_VERSION_2_1 = 0"

.PP
Definition at line \fB265\fP of file \fBglad\&.c\fP\&.
.SS "int GLAD_GL_VERSION_3_0 = 0"

.PP
Definition at line \fB266\fP of file \fBglad\&.c\fP\&.
.SS "int GLAD_GL_VERSION_3_1 = 0"

.PP
Definition at line \fB267\fP of file \fBglad\&.c\fP\&.
.SS "int GLAD_GL_VERSION_3_2 = 0"

.PP
Definition at line \fB268\fP of file \fBglad\&.c\fP\&.
.SS "int GLAD_GL_VERSION_3_3 = 0"

.PP
Definition at line \fB269\fP of file \fBglad\&.c\fP\&.
.SS "PFNGLACTIVETEXTUREPROC glad_glActiveTexture = NULL"

.PP
Definition at line \fB270\fP of file \fBglad\&.c\fP\&.
.SS "PFNGLATTACHSHADERPROC glad_glAttachShader = NULL"

.PP
Definition at line \fB271\fP of file \fBglad\&.c\fP\&.
.SS "PFNGLBEGINCONDITIONALRENDERPROC glad_glBeginConditionalRender = NULL"

.PP
Definition at line \fB272\fP of file \fBglad\&.c\fP\&.
.SS "PFNGLBEGINQUERYPROC glad_glBeginQuery = NULL"

.PP
Definition at line \fB273\fP of file \fBglad\&.c\fP\&.
.SS "PFNGLBEGINTRANSFORMFEEDBACKPROC glad_glBeginTransformFeedback = NULL"

.PP
Definition at line \fB274\fP of file \fBglad\&.c\fP\&.
.SS "PFNGLBINDATTRIBLOCATIONPROC glad_glBindAttribLocation = NULL"

.PP
Definition at line \fB275\fP of file \fBglad\&.c\fP\&.
.SS "PFNGLBINDBUFFERPROC glad_glBindBuffer = NULL"

.PP
Definition at line \fB276\fP of file \fBglad\&.c\fP\&.
.SS "PFNGLBINDBUFFERBASEPROC glad_glBindBufferBase = NULL"

.PP
Definition at line \fB277\fP of file \fBglad\&.c\fP\&.
.SS "PFNGLBINDBUFFERRANGEPROC glad_glBindBufferRange = NULL"

.PP
Definition at line \fB278\fP of file \fBglad\&.c\fP\&.
.SS "PFNGLBINDFRAGDATALOCATIONPROC glad_glBindFragDataLocation = NULL"

.PP
Definition at line \fB279\fP of file \fBglad\&.c\fP\&.
.SS "PFNGLBINDFRAGDATALOCATIONINDEXEDPROC glad_glBindFragDataLocationIndexed = NULL"

.PP
Definition at line \fB280\fP of file \fBglad\&.c\fP\&.
.SS "PFNGLBINDFRAMEBUFFERPROC glad_glBindFramebuffer = NULL"

.PP
Definition at line \fB281\fP of file \fBglad\&.c\fP\&.
.SS "PFNGLBINDRENDERBUFFERPROC glad_glBindRenderbuffer = NULL"

.PP
Definition at line \fB282\fP of file \fBglad\&.c\fP\&.
.SS "PFNGLBINDSAMPLERPROC glad_glBindSampler = NULL"

.PP
Definition at line \fB283\fP of file \fBglad\&.c\fP\&.
.SS "PFNGLBINDTEXTUREPROC glad_glBindTexture = NULL"

.PP
Definition at line \fB284\fP of file \fBglad\&.c\fP\&.
.SS "PFNGLBINDVERTEXARRAYPROC glad_glBindVertexArray = NULL"

.PP
Definition at line \fB285\fP of file \fBglad\&.c\fP\&.
.SS "PFNGLBLENDCOLORPROC glad_glBlendColor = NULL"

.PP
Definition at line \fB286\fP of file \fBglad\&.c\fP\&.
.SS "PFNGLBLENDEQUATIONPROC glad_glBlendEquation = NULL"

.PP
Definition at line \fB287\fP of file \fBglad\&.c\fP\&.
.SS "PFNGLBLENDEQUATIONSEPARATEPROC glad_glBlendEquationSeparate = NULL"

.PP
Definition at line \fB288\fP of file \fBglad\&.c\fP\&.
.SS "PFNGLBLENDFUNCPROC glad_glBlendFunc = NULL"

.PP
Definition at line \fB289\fP of file \fBglad\&.c\fP\&.
.SS "PFNGLBLENDFUNCSEPARATEPROC glad_glBlendFuncSeparate = NULL"

.PP
Definition at line \fB290\fP of file \fBglad\&.c\fP\&.
.SS "PFNGLBLITFRAMEBUFFERPROC glad_glBlitFramebuffer = NULL"

.PP
Definition at line \fB291\fP of file \fBglad\&.c\fP\&.
.SS "PFNGLBUFFERDATAPROC glad_glBufferData = NULL"

.PP
Definition at line \fB292\fP of file \fBglad\&.c\fP\&.
.SS "PFNGLBUFFERSUBDATAPROC glad_glBufferSubData = NULL"

.PP
Definition at line \fB293\fP of file \fBglad\&.c\fP\&.
.SS "PFNGLCHECKFRAMEBUFFERSTATUSPROC glad_glCheckFramebufferStatus = NULL"

.PP
Definition at line \fB294\fP of file \fBglad\&.c\fP\&.
.SS "PFNGLCLAMPCOLORPROC glad_glClampColor = NULL"

.PP
Definition at line \fB295\fP of file \fBglad\&.c\fP\&.
.SS "PFNGLCLEARPROC glad_glClear = NULL"

.PP
Definition at line \fB296\fP of file \fBglad\&.c\fP\&.
.SS "PFNGLCLEARBUFFERFIPROC glad_glClearBufferfi = NULL"

.PP
Definition at line \fB297\fP of file \fBglad\&.c\fP\&.
.SS "PFNGLCLEARBUFFERFVPROC glad_glClearBufferfv = NULL"

.PP
Definition at line \fB298\fP of file \fBglad\&.c\fP\&.
.SS "PFNGLCLEARBUFFERIVPROC glad_glClearBufferiv = NULL"

.PP
Definition at line \fB299\fP of file \fBglad\&.c\fP\&.
.SS "PFNGLCLEARBUFFERUIVPROC glad_glClearBufferuiv = NULL"

.PP
Definition at line \fB300\fP of file \fBglad\&.c\fP\&.
.SS "PFNGLCLEARCOLORPROC glad_glClearColor = NULL"

.PP
Definition at line \fB301\fP of file \fBglad\&.c\fP\&.
.SS "PFNGLCLEARDEPTHPROC glad_glClearDepth = NULL"

.PP
Definition at line \fB302\fP of file \fBglad\&.c\fP\&.
.SS "PFNGLCLEARSTENCILPROC glad_glClearStencil = NULL"

.PP
Definition at line \fB303\fP of file \fBglad\&.c\fP\&.
.SS "PFNGLCLIENTWAITSYNCPROC glad_glClientWaitSync = NULL"

.PP
Definition at line \fB304\fP of file \fBglad\&.c\fP\&.
.SS "PFNGLCOLORMASKPROC glad_glColorMask = NULL"

.PP
Definition at line \fB305\fP of file \fBglad\&.c\fP\&.
.SS "PFNGLCOLORMASKIPROC glad_glColorMaski = NULL"

.PP
Definition at line \fB306\fP of file \fBglad\&.c\fP\&.
.SS "PFNGLCOLORP3UIPROC glad_glColorP3ui = NULL"

.PP
Definition at line \fB307\fP of file \fBglad\&.c\fP\&.
.SS "PFNGLCOLORP3UIVPROC glad_glColorP3uiv = NULL"

.PP
Definition at line \fB308\fP of file \fBglad\&.c\fP\&.
.SS "PFNGLCOLORP4UIPROC glad_glColorP4ui = NULL"

.PP
Definition at line \fB309\fP of file \fBglad\&.c\fP\&.
.SS "PFNGLCOLORP4UIVPROC glad_glColorP4uiv = NULL"

.PP
Definition at line \fB310\fP of file \fBglad\&.c\fP\&.
.SS "PFNGLCOMPILESHADERPROC glad_glCompileShader = NULL"

.PP
Definition at line \fB311\fP of file \fBglad\&.c\fP\&.
.SS "PFNGLCOMPRESSEDTEXIMAGE1DPROC glad_glCompressedTexImage1D = NULL"

.PP
Definition at line \fB312\fP of file \fBglad\&.c\fP\&.
.SS "PFNGLCOMPRESSEDTEXIMAGE2DPROC glad_glCompressedTexImage2D = NULL"

.PP
Definition at line \fB313\fP of file \fBglad\&.c\fP\&.
.SS "PFNGLCOMPRESSEDTEXIMAGE3DPROC glad_glCompressedTexImage3D = NULL"

.PP
Definition at line \fB314\fP of file \fBglad\&.c\fP\&.
.SS "PFNGLCOMPRESSEDTEXSUBIMAGE1DPROC glad_glCompressedTexSubImage1D = NULL"

.PP
Definition at line \fB315\fP of file \fBglad\&.c\fP\&.
.SS "PFNGLCOMPRESSEDTEXSUBIMAGE2DPROC glad_glCompressedTexSubImage2D = NULL"

.PP
Definition at line \fB316\fP of file \fBglad\&.c\fP\&.
.SS "PFNGLCOMPRESSEDTEXSUBIMAGE3DPROC glad_glCompressedTexSubImage3D = NULL"

.PP
Definition at line \fB317\fP of file \fBglad\&.c\fP\&.
.SS "PFNGLCOPYBUFFERSUBDATAPROC glad_glCopyBufferSubData = NULL"

.PP
Definition at line \fB318\fP of file \fBglad\&.c\fP\&.
.SS "PFNGLCOPYTEXIMAGE1DPROC glad_glCopyTexImage1D = NULL"

.PP
Definition at line \fB319\fP of file \fBglad\&.c\fP\&.
.SS "PFNGLCOPYTEXIMAGE2DPROC glad_glCopyTexImage2D = NULL"

.PP
Definition at line \fB320\fP of file \fBglad\&.c\fP\&.
.SS "PFNGLCOPYTEXSUBIMAGE1DPROC glad_glCopyTexSubImage1D = NULL"

.PP
Definition at line \fB321\fP of file \fBglad\&.c\fP\&.
.SS "PFNGLCOPYTEXSUBIMAGE2DPROC glad_glCopyTexSubImage2D = NULL"

.PP
Definition at line \fB322\fP of file \fBglad\&.c\fP\&.
.SS "PFNGLCOPYTEXSUBIMAGE3DPROC glad_glCopyTexSubImage3D = NULL"

.PP
Definition at line \fB323\fP of file \fBglad\&.c\fP\&.
.SS "PFNGLCREATEPROGRAMPROC glad_glCreateProgram = NULL"

.PP
Definition at line \fB324\fP of file \fBglad\&.c\fP\&.
.SS "PFNGLCREATESHADERPROC glad_glCreateShader = NULL"

.PP
Definition at line \fB325\fP of file \fBglad\&.c\fP\&.
.SS "PFNGLCULLFACEPROC glad_glCullFace = NULL"

.PP
Definition at line \fB326\fP of file \fBglad\&.c\fP\&.
.SS "PFNGLDELETEBUFFERSPROC glad_glDeleteBuffers = NULL"

.PP
Definition at line \fB327\fP of file \fBglad\&.c\fP\&.
.SS "PFNGLDELETEFRAMEBUFFERSPROC glad_glDeleteFramebuffers = NULL"

.PP
Definition at line \fB328\fP of file \fBglad\&.c\fP\&.
.SS "PFNGLDELETEPROGRAMPROC glad_glDeleteProgram = NULL"

.PP
Definition at line \fB329\fP of file \fBglad\&.c\fP\&.
.SS "PFNGLDELETEQUERIESPROC glad_glDeleteQueries = NULL"

.PP
Definition at line \fB330\fP of file \fBglad\&.c\fP\&.
.SS "PFNGLDELETERENDERBUFFERSPROC glad_glDeleteRenderbuffers = NULL"

.PP
Definition at line \fB331\fP of file \fBglad\&.c\fP\&.
.SS "PFNGLDELETESAMPLERSPROC glad_glDeleteSamplers = NULL"

.PP
Definition at line \fB332\fP of file \fBglad\&.c\fP\&.
.SS "PFNGLDELETESHADERPROC glad_glDeleteShader = NULL"

.PP
Definition at line \fB333\fP of file \fBglad\&.c\fP\&.
.SS "PFNGLDELETESYNCPROC glad_glDeleteSync = NULL"

.PP
Definition at line \fB334\fP of file \fBglad\&.c\fP\&.
.SS "PFNGLDELETETEXTURESPROC glad_glDeleteTextures = NULL"

.PP
Definition at line \fB335\fP of file \fBglad\&.c\fP\&.
.SS "PFNGLDELETEVERTEXARRAYSPROC glad_glDeleteVertexArrays = NULL"

.PP
Definition at line \fB336\fP of file \fBglad\&.c\fP\&.
.SS "PFNGLDEPTHFUNCPROC glad_glDepthFunc = NULL"

.PP
Definition at line \fB337\fP of file \fBglad\&.c\fP\&.
.SS "PFNGLDEPTHMASKPROC glad_glDepthMask = NULL"

.PP
Definition at line \fB338\fP of file \fBglad\&.c\fP\&.
.SS "PFNGLDEPTHRANGEPROC glad_glDepthRange = NULL"

.PP
Definition at line \fB339\fP of file \fBglad\&.c\fP\&.
.SS "PFNGLDETACHSHADERPROC glad_glDetachShader = NULL"

.PP
Definition at line \fB340\fP of file \fBglad\&.c\fP\&.
.SS "PFNGLDISABLEPROC glad_glDisable = NULL"

.PP
Definition at line \fB341\fP of file \fBglad\&.c\fP\&.
.SS "PFNGLDISABLEIPROC glad_glDisablei = NULL"

.PP
Definition at line \fB343\fP of file \fBglad\&.c\fP\&.
.SS "PFNGLDISABLEVERTEXATTRIBARRAYPROC glad_glDisableVertexAttribArray = NULL"

.PP
Definition at line \fB342\fP of file \fBglad\&.c\fP\&.
.SS "PFNGLDRAWARRAYSPROC glad_glDrawArrays = NULL"

.PP
Definition at line \fB344\fP of file \fBglad\&.c\fP\&.
.SS "PFNGLDRAWARRAYSINSTANCEDPROC glad_glDrawArraysInstanced = NULL"

.PP
Definition at line \fB345\fP of file \fBglad\&.c\fP\&.
.SS "PFNGLDRAWBUFFERPROC glad_glDrawBuffer = NULL"

.PP
Definition at line \fB346\fP of file \fBglad\&.c\fP\&.
.SS "PFNGLDRAWBUFFERSPROC glad_glDrawBuffers = NULL"

.PP
Definition at line \fB347\fP of file \fBglad\&.c\fP\&.
.SS "PFNGLDRAWELEMENTSPROC glad_glDrawElements = NULL"

.PP
Definition at line \fB348\fP of file \fBglad\&.c\fP\&.
.SS "PFNGLDRAWELEMENTSBASEVERTEXPROC glad_glDrawElementsBaseVertex = NULL"

.PP
Definition at line \fB349\fP of file \fBglad\&.c\fP\&.
.SS "PFNGLDRAWELEMENTSINSTANCEDPROC glad_glDrawElementsInstanced = NULL"

.PP
Definition at line \fB350\fP of file \fBglad\&.c\fP\&.
.SS "PFNGLDRAWELEMENTSINSTANCEDBASEVERTEXPROC glad_glDrawElementsInstancedBaseVertex = NULL"

.PP
Definition at line \fB351\fP of file \fBglad\&.c\fP\&.
.SS "PFNGLDRAWRANGEELEMENTSPROC glad_glDrawRangeElements = NULL"

.PP
Definition at line \fB352\fP of file \fBglad\&.c\fP\&.
.SS "PFNGLDRAWRANGEELEMENTSBASEVERTEXPROC glad_glDrawRangeElementsBaseVertex = NULL"

.PP
Definition at line \fB353\fP of file \fBglad\&.c\fP\&.
.SS "PFNGLENABLEPROC glad_glEnable = NULL"

.PP
Definition at line \fB354\fP of file \fBglad\&.c\fP\&.
.SS "PFNGLENABLEIPROC glad_glEnablei = NULL"

.PP
Definition at line \fB356\fP of file \fBglad\&.c\fP\&.
.SS "PFNGLENABLEVERTEXATTRIBARRAYPROC glad_glEnableVertexAttribArray = NULL"

.PP
Definition at line \fB355\fP of file \fBglad\&.c\fP\&.
.SS "PFNGLENDCONDITIONALRENDERPROC glad_glEndConditionalRender = NULL"

.PP
Definition at line \fB357\fP of file \fBglad\&.c\fP\&.
.SS "PFNGLENDQUERYPROC glad_glEndQuery = NULL"

.PP
Definition at line \fB358\fP of file \fBglad\&.c\fP\&.
.SS "PFNGLENDTRANSFORMFEEDBACKPROC glad_glEndTransformFeedback = NULL"

.PP
Definition at line \fB359\fP of file \fBglad\&.c\fP\&.
.SS "PFNGLFENCESYNCPROC glad_glFenceSync = NULL"

.PP
Definition at line \fB360\fP of file \fBglad\&.c\fP\&.
.SS "PFNGLFINISHPROC glad_glFinish = NULL"

.PP
Definition at line \fB361\fP of file \fBglad\&.c\fP\&.
.SS "PFNGLFLUSHPROC glad_glFlush = NULL"

.PP
Definition at line \fB362\fP of file \fBglad\&.c\fP\&.
.SS "PFNGLFLUSHMAPPEDBUFFERRANGEPROC glad_glFlushMappedBufferRange = NULL"

.PP
Definition at line \fB363\fP of file \fBglad\&.c\fP\&.
.SS "PFNGLFRAMEBUFFERRENDERBUFFERPROC glad_glFramebufferRenderbuffer = NULL"

.PP
Definition at line \fB364\fP of file \fBglad\&.c\fP\&.
.SS "PFNGLFRAMEBUFFERTEXTUREPROC glad_glFramebufferTexture = NULL"

.PP
Definition at line \fB365\fP of file \fBglad\&.c\fP\&.
.SS "PFNGLFRAMEBUFFERTEXTURE1DPROC glad_glFramebufferTexture1D = NULL"

.PP
Definition at line \fB366\fP of file \fBglad\&.c\fP\&.
.SS "PFNGLFRAMEBUFFERTEXTURE2DPROC glad_glFramebufferTexture2D = NULL"

.PP
Definition at line \fB367\fP of file \fBglad\&.c\fP\&.
.SS "PFNGLFRAMEBUFFERTEXTURE3DPROC glad_glFramebufferTexture3D = NULL"

.PP
Definition at line \fB368\fP of file \fBglad\&.c\fP\&.
.SS "PFNGLFRAMEBUFFERTEXTURELAYERPROC glad_glFramebufferTextureLayer = NULL"

.PP
Definition at line \fB369\fP of file \fBglad\&.c\fP\&.
.SS "PFNGLFRONTFACEPROC glad_glFrontFace = NULL"

.PP
Definition at line \fB370\fP of file \fBglad\&.c\fP\&.
.SS "PFNGLGENBUFFERSPROC glad_glGenBuffers = NULL"

.PP
Definition at line \fB371\fP of file \fBglad\&.c\fP\&.
.SS "PFNGLGENERATEMIPMAPPROC glad_glGenerateMipmap = NULL"

.PP
Definition at line \fB378\fP of file \fBglad\&.c\fP\&.
.SS "PFNGLGENFRAMEBUFFERSPROC glad_glGenFramebuffers = NULL"

.PP
Definition at line \fB372\fP of file \fBglad\&.c\fP\&.
.SS "PFNGLGENQUERIESPROC glad_glGenQueries = NULL"

.PP
Definition at line \fB373\fP of file \fBglad\&.c\fP\&.
.SS "PFNGLGENRENDERBUFFERSPROC glad_glGenRenderbuffers = NULL"

.PP
Definition at line \fB374\fP of file \fBglad\&.c\fP\&.
.SS "PFNGLGENSAMPLERSPROC glad_glGenSamplers = NULL"

.PP
Definition at line \fB375\fP of file \fBglad\&.c\fP\&.
.SS "PFNGLGENTEXTURESPROC glad_glGenTextures = NULL"

.PP
Definition at line \fB376\fP of file \fBglad\&.c\fP\&.
.SS "PFNGLGENVERTEXARRAYSPROC glad_glGenVertexArrays = NULL"

.PP
Definition at line \fB377\fP of file \fBglad\&.c\fP\&.
.SS "PFNGLGETACTIVEATTRIBPROC glad_glGetActiveAttrib = NULL"

.PP
Definition at line \fB379\fP of file \fBglad\&.c\fP\&.
.SS "PFNGLGETACTIVEUNIFORMPROC glad_glGetActiveUniform = NULL"

.PP
Definition at line \fB380\fP of file \fBglad\&.c\fP\&.
.SS "PFNGLGETACTIVEUNIFORMBLOCKIVPROC glad_glGetActiveUniformBlockiv = NULL"

.PP
Definition at line \fB382\fP of file \fBglad\&.c\fP\&.
.SS "PFNGLGETACTIVEUNIFORMBLOCKNAMEPROC glad_glGetActiveUniformBlockName = NULL"

.PP
Definition at line \fB381\fP of file \fBglad\&.c\fP\&.
.SS "PFNGLGETACTIVEUNIFORMNAMEPROC glad_glGetActiveUniformName = NULL"

.PP
Definition at line \fB383\fP of file \fBglad\&.c\fP\&.
.SS "PFNGLGETACTIVEUNIFORMSIVPROC glad_glGetActiveUniformsiv = NULL"

.PP
Definition at line \fB384\fP of file \fBglad\&.c\fP\&.
.SS "PFNGLGETATTACHEDSHADERSPROC glad_glGetAttachedShaders = NULL"

.PP
Definition at line \fB385\fP of file \fBglad\&.c\fP\&.
.SS "PFNGLGETATTRIBLOCATIONPROC glad_glGetAttribLocation = NULL"

.PP
Definition at line \fB386\fP of file \fBglad\&.c\fP\&.
.SS "PFNGLGETBOOLEANI_VPROC glad_glGetBooleani_v = NULL"

.PP
Definition at line \fB387\fP of file \fBglad\&.c\fP\&.
.SS "PFNGLGETBOOLEANVPROC glad_glGetBooleanv = NULL"

.PP
Definition at line \fB388\fP of file \fBglad\&.c\fP\&.
.SS "PFNGLGETBUFFERPARAMETERI64VPROC glad_glGetBufferParameteri64v = NULL"

.PP
Definition at line \fB389\fP of file \fBglad\&.c\fP\&.
.SS "PFNGLGETBUFFERPARAMETERIVPROC glad_glGetBufferParameteriv = NULL"

.PP
Definition at line \fB390\fP of file \fBglad\&.c\fP\&.
.SS "PFNGLGETBUFFERPOINTERVPROC glad_glGetBufferPointerv = NULL"

.PP
Definition at line \fB391\fP of file \fBglad\&.c\fP\&.
.SS "PFNGLGETBUFFERSUBDATAPROC glad_glGetBufferSubData = NULL"

.PP
Definition at line \fB392\fP of file \fBglad\&.c\fP\&.
.SS "PFNGLGETCOMPRESSEDTEXIMAGEPROC glad_glGetCompressedTexImage = NULL"

.PP
Definition at line \fB393\fP of file \fBglad\&.c\fP\&.
.SS "PFNGLGETDOUBLEVPROC glad_glGetDoublev = NULL"

.PP
Definition at line \fB394\fP of file \fBglad\&.c\fP\&.
.SS "PFNGLGETERRORPROC glad_glGetError = NULL"

.PP
Definition at line \fB395\fP of file \fBglad\&.c\fP\&.
.SS "PFNGLGETFLOATVPROC glad_glGetFloatv = NULL"

.PP
Definition at line \fB396\fP of file \fBglad\&.c\fP\&.
.SS "PFNGLGETFRAGDATAINDEXPROC glad_glGetFragDataIndex = NULL"

.PP
Definition at line \fB397\fP of file \fBglad\&.c\fP\&.
.SS "PFNGLGETFRAGDATALOCATIONPROC glad_glGetFragDataLocation = NULL"

.PP
Definition at line \fB398\fP of file \fBglad\&.c\fP\&.
.SS "PFNGLGETFRAMEBUFFERATTACHMENTPARAMETERIVPROC glad_glGetFramebufferAttachmentParameteriv = NULL"

.PP
Definition at line \fB399\fP of file \fBglad\&.c\fP\&.
.SS "PFNGLGETINTEGER64I_VPROC glad_glGetInteger64i_v = NULL"

.PP
Definition at line \fB400\fP of file \fBglad\&.c\fP\&.
.SS "PFNGLGETINTEGER64VPROC glad_glGetInteger64v = NULL"

.PP
Definition at line \fB401\fP of file \fBglad\&.c\fP\&.
.SS "PFNGLGETINTEGERI_VPROC glad_glGetIntegeri_v = NULL"

.PP
Definition at line \fB402\fP of file \fBglad\&.c\fP\&.
.SS "PFNGLGETINTEGERVPROC glad_glGetIntegerv = NULL"

.PP
Definition at line \fB403\fP of file \fBglad\&.c\fP\&.
.SS "PFNGLGETMULTISAMPLEFVPROC glad_glGetMultisamplefv = NULL"

.PP
Definition at line \fB404\fP of file \fBglad\&.c\fP\&.
.SS "PFNGLGETPROGRAMINFOLOGPROC glad_glGetProgramInfoLog = NULL"

.PP
Definition at line \fB405\fP of file \fBglad\&.c\fP\&.
.SS "PFNGLGETPROGRAMIVPROC glad_glGetProgramiv = NULL"

.PP
Definition at line \fB406\fP of file \fBglad\&.c\fP\&.
.SS "PFNGLGETQUERYIVPROC glad_glGetQueryiv = NULL"

.PP
Definition at line \fB411\fP of file \fBglad\&.c\fP\&.
.SS "PFNGLGETQUERYOBJECTI64VPROC glad_glGetQueryObjecti64v = NULL"

.PP
Definition at line \fB407\fP of file \fBglad\&.c\fP\&.
.SS "PFNGLGETQUERYOBJECTIVPROC glad_glGetQueryObjectiv = NULL"

.PP
Definition at line \fB408\fP of file \fBglad\&.c\fP\&.
.SS "PFNGLGETQUERYOBJECTUI64VPROC glad_glGetQueryObjectui64v = NULL"

.PP
Definition at line \fB409\fP of file \fBglad\&.c\fP\&.
.SS "PFNGLGETQUERYOBJECTUIVPROC glad_glGetQueryObjectuiv = NULL"

.PP
Definition at line \fB410\fP of file \fBglad\&.c\fP\&.
.SS "PFNGLGETRENDERBUFFERPARAMETERIVPROC glad_glGetRenderbufferParameteriv = NULL"

.PP
Definition at line \fB412\fP of file \fBglad\&.c\fP\&.
.SS "PFNGLGETSAMPLERPARAMETERFVPROC glad_glGetSamplerParameterfv = NULL"

.PP
Definition at line \fB415\fP of file \fBglad\&.c\fP\&.
.SS "PFNGLGETSAMPLERPARAMETERIIVPROC glad_glGetSamplerParameterIiv = NULL"

.PP
Definition at line \fB413\fP of file \fBglad\&.c\fP\&.
.SS "PFNGLGETSAMPLERPARAMETERIUIVPROC glad_glGetSamplerParameterIuiv = NULL"

.PP
Definition at line \fB414\fP of file \fBglad\&.c\fP\&.
.SS "PFNGLGETSAMPLERPARAMETERIVPROC glad_glGetSamplerParameteriv = NULL"

.PP
Definition at line \fB416\fP of file \fBglad\&.c\fP\&.
.SS "PFNGLGETSHADERINFOLOGPROC glad_glGetShaderInfoLog = NULL"

.PP
Definition at line \fB417\fP of file \fBglad\&.c\fP\&.
.SS "PFNGLGETSHADERIVPROC glad_glGetShaderiv = NULL"

.PP
Definition at line \fB419\fP of file \fBglad\&.c\fP\&.
.SS "PFNGLGETSHADERSOURCEPROC glad_glGetShaderSource = NULL"

.PP
Definition at line \fB418\fP of file \fBglad\&.c\fP\&.
.SS "PFNGLGETSTRINGPROC glad_glGetString = NULL"

.PP
Definition at line \fB420\fP of file \fBglad\&.c\fP\&.
.SS "PFNGLGETSTRINGIPROC glad_glGetStringi = NULL"

.PP
Definition at line \fB421\fP of file \fBglad\&.c\fP\&.
.SS "PFNGLGETSYNCIVPROC glad_glGetSynciv = NULL"

.PP
Definition at line \fB422\fP of file \fBglad\&.c\fP\&.
.SS "PFNGLGETTEXIMAGEPROC glad_glGetTexImage = NULL"

.PP
Definition at line \fB423\fP of file \fBglad\&.c\fP\&.
.SS "PFNGLGETTEXLEVELPARAMETERFVPROC glad_glGetTexLevelParameterfv = NULL"

.PP
Definition at line \fB424\fP of file \fBglad\&.c\fP\&.
.SS "PFNGLGETTEXLEVELPARAMETERIVPROC glad_glGetTexLevelParameteriv = NULL"

.PP
Definition at line \fB425\fP of file \fBglad\&.c\fP\&.
.SS "PFNGLGETTEXPARAMETERFVPROC glad_glGetTexParameterfv = NULL"

.PP
Definition at line \fB428\fP of file \fBglad\&.c\fP\&.
.SS "PFNGLGETTEXPARAMETERIIVPROC glad_glGetTexParameterIiv = NULL"

.PP
Definition at line \fB426\fP of file \fBglad\&.c\fP\&.
.SS "PFNGLGETTEXPARAMETERIUIVPROC glad_glGetTexParameterIuiv = NULL"

.PP
Definition at line \fB427\fP of file \fBglad\&.c\fP\&.
.SS "PFNGLGETTEXPARAMETERIVPROC glad_glGetTexParameteriv = NULL"

.PP
Definition at line \fB429\fP of file \fBglad\&.c\fP\&.
.SS "PFNGLGETTRANSFORMFEEDBACKVARYINGPROC glad_glGetTransformFeedbackVarying = NULL"

.PP
Definition at line \fB430\fP of file \fBglad\&.c\fP\&.
.SS "PFNGLGETUNIFORMBLOCKINDEXPROC glad_glGetUniformBlockIndex = NULL"

.PP
Definition at line \fB431\fP of file \fBglad\&.c\fP\&.
.SS "PFNGLGETUNIFORMFVPROC glad_glGetUniformfv = NULL"

.PP
Definition at line \fB434\fP of file \fBglad\&.c\fP\&.
.SS "PFNGLGETUNIFORMINDICESPROC glad_glGetUniformIndices = NULL"

.PP
Definition at line \fB432\fP of file \fBglad\&.c\fP\&.
.SS "PFNGLGETUNIFORMIVPROC glad_glGetUniformiv = NULL"

.PP
Definition at line \fB435\fP of file \fBglad\&.c\fP\&.
.SS "PFNGLGETUNIFORMLOCATIONPROC glad_glGetUniformLocation = NULL"

.PP
Definition at line \fB433\fP of file \fBglad\&.c\fP\&.
.SS "PFNGLGETUNIFORMUIVPROC glad_glGetUniformuiv = NULL"

.PP
Definition at line \fB436\fP of file \fBglad\&.c\fP\&.
.SS "PFNGLGETVERTEXATTRIBDVPROC glad_glGetVertexAttribdv = NULL"

.PP
Definition at line \fB440\fP of file \fBglad\&.c\fP\&.
.SS "PFNGLGETVERTEXATTRIBFVPROC glad_glGetVertexAttribfv = NULL"

.PP
Definition at line \fB441\fP of file \fBglad\&.c\fP\&.
.SS "PFNGLGETVERTEXATTRIBIIVPROC glad_glGetVertexAttribIiv = NULL"

.PP
Definition at line \fB437\fP of file \fBglad\&.c\fP\&.
.SS "PFNGLGETVERTEXATTRIBIUIVPROC glad_glGetVertexAttribIuiv = NULL"

.PP
Definition at line \fB438\fP of file \fBglad\&.c\fP\&.
.SS "PFNGLGETVERTEXATTRIBIVPROC glad_glGetVertexAttribiv = NULL"

.PP
Definition at line \fB442\fP of file \fBglad\&.c\fP\&.
.SS "PFNGLGETVERTEXATTRIBPOINTERVPROC glad_glGetVertexAttribPointerv = NULL"

.PP
Definition at line \fB439\fP of file \fBglad\&.c\fP\&.
.SS "PFNGLHINTPROC glad_glHint = NULL"

.PP
Definition at line \fB443\fP of file \fBglad\&.c\fP\&.
.SS "PFNGLISBUFFERPROC glad_glIsBuffer = NULL"

.PP
Definition at line \fB444\fP of file \fBglad\&.c\fP\&.
.SS "PFNGLISENABLEDPROC glad_glIsEnabled = NULL"

.PP
Definition at line \fB445\fP of file \fBglad\&.c\fP\&.
.SS "PFNGLISENABLEDIPROC glad_glIsEnabledi = NULL"

.PP
Definition at line \fB446\fP of file \fBglad\&.c\fP\&.
.SS "PFNGLISFRAMEBUFFERPROC glad_glIsFramebuffer = NULL"

.PP
Definition at line \fB447\fP of file \fBglad\&.c\fP\&.
.SS "PFNGLISPROGRAMPROC glad_glIsProgram = NULL"

.PP
Definition at line \fB448\fP of file \fBglad\&.c\fP\&.
.SS "PFNGLISQUERYPROC glad_glIsQuery = NULL"

.PP
Definition at line \fB449\fP of file \fBglad\&.c\fP\&.
.SS "PFNGLISRENDERBUFFERPROC glad_glIsRenderbuffer = NULL"

.PP
Definition at line \fB450\fP of file \fBglad\&.c\fP\&.
.SS "PFNGLISSAMPLERPROC glad_glIsSampler = NULL"

.PP
Definition at line \fB451\fP of file \fBglad\&.c\fP\&.
.SS "PFNGLISSHADERPROC glad_glIsShader = NULL"

.PP
Definition at line \fB452\fP of file \fBglad\&.c\fP\&.
.SS "PFNGLISSYNCPROC glad_glIsSync = NULL"

.PP
Definition at line \fB453\fP of file \fBglad\&.c\fP\&.
.SS "PFNGLISTEXTUREPROC glad_glIsTexture = NULL"

.PP
Definition at line \fB454\fP of file \fBglad\&.c\fP\&.
.SS "PFNGLISVERTEXARRAYPROC glad_glIsVertexArray = NULL"

.PP
Definition at line \fB455\fP of file \fBglad\&.c\fP\&.
.SS "PFNGLLINEWIDTHPROC glad_glLineWidth = NULL"

.PP
Definition at line \fB456\fP of file \fBglad\&.c\fP\&.
.SS "PFNGLLINKPROGRAMPROC glad_glLinkProgram = NULL"

.PP
Definition at line \fB457\fP of file \fBglad\&.c\fP\&.
.SS "PFNGLLOGICOPPROC glad_glLogicOp = NULL"

.PP
Definition at line \fB458\fP of file \fBglad\&.c\fP\&.
.SS "PFNGLMAPBUFFERPROC glad_glMapBuffer = NULL"

.PP
Definition at line \fB459\fP of file \fBglad\&.c\fP\&.
.SS "PFNGLMAPBUFFERRANGEPROC glad_glMapBufferRange = NULL"

.PP
Definition at line \fB460\fP of file \fBglad\&.c\fP\&.
.SS "PFNGLMULTIDRAWARRAYSPROC glad_glMultiDrawArrays = NULL"

.PP
Definition at line \fB461\fP of file \fBglad\&.c\fP\&.
.SS "PFNGLMULTIDRAWELEMENTSPROC glad_glMultiDrawElements = NULL"

.PP
Definition at line \fB462\fP of file \fBglad\&.c\fP\&.
.SS "PFNGLMULTIDRAWELEMENTSBASEVERTEXPROC glad_glMultiDrawElementsBaseVertex = NULL"

.PP
Definition at line \fB463\fP of file \fBglad\&.c\fP\&.
.SS "PFNGLMULTITEXCOORDP1UIPROC glad_glMultiTexCoordP1ui = NULL"

.PP
Definition at line \fB464\fP of file \fBglad\&.c\fP\&.
.SS "PFNGLMULTITEXCOORDP1UIVPROC glad_glMultiTexCoordP1uiv = NULL"

.PP
Definition at line \fB465\fP of file \fBglad\&.c\fP\&.
.SS "PFNGLMULTITEXCOORDP2UIPROC glad_glMultiTexCoordP2ui = NULL"

.PP
Definition at line \fB466\fP of file \fBglad\&.c\fP\&.
.SS "PFNGLMULTITEXCOORDP2UIVPROC glad_glMultiTexCoordP2uiv = NULL"

.PP
Definition at line \fB467\fP of file \fBglad\&.c\fP\&.
.SS "PFNGLMULTITEXCOORDP3UIPROC glad_glMultiTexCoordP3ui = NULL"

.PP
Definition at line \fB468\fP of file \fBglad\&.c\fP\&.
.SS "PFNGLMULTITEXCOORDP3UIVPROC glad_glMultiTexCoordP3uiv = NULL"

.PP
Definition at line \fB469\fP of file \fBglad\&.c\fP\&.
.SS "PFNGLMULTITEXCOORDP4UIPROC glad_glMultiTexCoordP4ui = NULL"

.PP
Definition at line \fB470\fP of file \fBglad\&.c\fP\&.
.SS "PFNGLMULTITEXCOORDP4UIVPROC glad_glMultiTexCoordP4uiv = NULL"

.PP
Definition at line \fB471\fP of file \fBglad\&.c\fP\&.
.SS "PFNGLNORMALP3UIPROC glad_glNormalP3ui = NULL"

.PP
Definition at line \fB472\fP of file \fBglad\&.c\fP\&.
.SS "PFNGLNORMALP3UIVPROC glad_glNormalP3uiv = NULL"

.PP
Definition at line \fB473\fP of file \fBglad\&.c\fP\&.
.SS "PFNGLPIXELSTOREFPROC glad_glPixelStoref = NULL"

.PP
Definition at line \fB474\fP of file \fBglad\&.c\fP\&.
.SS "PFNGLPIXELSTOREIPROC glad_glPixelStorei = NULL"

.PP
Definition at line \fB475\fP of file \fBglad\&.c\fP\&.
.SS "PFNGLPOINTPARAMETERFPROC glad_glPointParameterf = NULL"

.PP
Definition at line \fB476\fP of file \fBglad\&.c\fP\&.
.SS "PFNGLPOINTPARAMETERFVPROC glad_glPointParameterfv = NULL"

.PP
Definition at line \fB477\fP of file \fBglad\&.c\fP\&.
.SS "PFNGLPOINTPARAMETERIPROC glad_glPointParameteri = NULL"

.PP
Definition at line \fB478\fP of file \fBglad\&.c\fP\&.
.SS "PFNGLPOINTPARAMETERIVPROC glad_glPointParameteriv = NULL"

.PP
Definition at line \fB479\fP of file \fBglad\&.c\fP\&.
.SS "PFNGLPOINTSIZEPROC glad_glPointSize = NULL"

.PP
Definition at line \fB480\fP of file \fBglad\&.c\fP\&.
.SS "PFNGLPOLYGONMODEPROC glad_glPolygonMode = NULL"

.PP
Definition at line \fB481\fP of file \fBglad\&.c\fP\&.
.SS "PFNGLPOLYGONOFFSETPROC glad_glPolygonOffset = NULL"

.PP
Definition at line \fB482\fP of file \fBglad\&.c\fP\&.
.SS "PFNGLPRIMITIVERESTARTINDEXPROC glad_glPrimitiveRestartIndex = NULL"

.PP
Definition at line \fB483\fP of file \fBglad\&.c\fP\&.
.SS "PFNGLPROVOKINGVERTEXPROC glad_glProvokingVertex = NULL"

.PP
Definition at line \fB484\fP of file \fBglad\&.c\fP\&.
.SS "PFNGLQUERYCOUNTERPROC glad_glQueryCounter = NULL"

.PP
Definition at line \fB485\fP of file \fBglad\&.c\fP\&.
.SS "PFNGLREADBUFFERPROC glad_glReadBuffer = NULL"

.PP
Definition at line \fB486\fP of file \fBglad\&.c\fP\&.
.SS "PFNGLREADPIXELSPROC glad_glReadPixels = NULL"

.PP
Definition at line \fB487\fP of file \fBglad\&.c\fP\&.
.SS "PFNGLRENDERBUFFERSTORAGEPROC glad_glRenderbufferStorage = NULL"

.PP
Definition at line \fB488\fP of file \fBglad\&.c\fP\&.
.SS "PFNGLRENDERBUFFERSTORAGEMULTISAMPLEPROC glad_glRenderbufferStorageMultisample = NULL"

.PP
Definition at line \fB489\fP of file \fBglad\&.c\fP\&.
.SS "PFNGLSAMPLECOVERAGEPROC glad_glSampleCoverage = NULL"

.PP
Definition at line \fB490\fP of file \fBglad\&.c\fP\&.
.SS "PFNGLSAMPLEMASKIPROC glad_glSampleMaski = NULL"

.PP
Definition at line \fB491\fP of file \fBglad\&.c\fP\&.
.SS "PFNGLSAMPLERPARAMETERFPROC glad_glSamplerParameterf = NULL"

.PP
Definition at line \fB494\fP of file \fBglad\&.c\fP\&.
.SS "PFNGLSAMPLERPARAMETERFVPROC glad_glSamplerParameterfv = NULL"

.PP
Definition at line \fB495\fP of file \fBglad\&.c\fP\&.
.SS "PFNGLSAMPLERPARAMETERIPROC glad_glSamplerParameteri = NULL"

.PP
Definition at line \fB496\fP of file \fBglad\&.c\fP\&.
.SS "PFNGLSAMPLERPARAMETERIIVPROC glad_glSamplerParameterIiv = NULL"

.PP
Definition at line \fB492\fP of file \fBglad\&.c\fP\&.
.SS "PFNGLSAMPLERPARAMETERIUIVPROC glad_glSamplerParameterIuiv = NULL"

.PP
Definition at line \fB493\fP of file \fBglad\&.c\fP\&.
.SS "PFNGLSAMPLERPARAMETERIVPROC glad_glSamplerParameteriv = NULL"

.PP
Definition at line \fB497\fP of file \fBglad\&.c\fP\&.
.SS "PFNGLSCISSORPROC glad_glScissor = NULL"

.PP
Definition at line \fB498\fP of file \fBglad\&.c\fP\&.
.SS "PFNGLSECONDARYCOLORP3UIPROC glad_glSecondaryColorP3ui = NULL"

.PP
Definition at line \fB499\fP of file \fBglad\&.c\fP\&.
.SS "PFNGLSECONDARYCOLORP3UIVPROC glad_glSecondaryColorP3uiv = NULL"

.PP
Definition at line \fB500\fP of file \fBglad\&.c\fP\&.
.SS "PFNGLSHADERSOURCEPROC glad_glShaderSource = NULL"

.PP
Definition at line \fB501\fP of file \fBglad\&.c\fP\&.
.SS "PFNGLSTENCILFUNCPROC glad_glStencilFunc = NULL"

.PP
Definition at line \fB502\fP of file \fBglad\&.c\fP\&.
.SS "PFNGLSTENCILFUNCSEPARATEPROC glad_glStencilFuncSeparate = NULL"

.PP
Definition at line \fB503\fP of file \fBglad\&.c\fP\&.
.SS "PFNGLSTENCILMASKPROC glad_glStencilMask = NULL"

.PP
Definition at line \fB504\fP of file \fBglad\&.c\fP\&.
.SS "PFNGLSTENCILMASKSEPARATEPROC glad_glStencilMaskSeparate = NULL"

.PP
Definition at line \fB505\fP of file \fBglad\&.c\fP\&.
.SS "PFNGLSTENCILOPPROC glad_glStencilOp = NULL"

.PP
Definition at line \fB506\fP of file \fBglad\&.c\fP\&.
.SS "PFNGLSTENCILOPSEPARATEPROC glad_glStencilOpSeparate = NULL"

.PP
Definition at line \fB507\fP of file \fBglad\&.c\fP\&.
.SS "PFNGLTEXBUFFERPROC glad_glTexBuffer = NULL"

.PP
Definition at line \fB508\fP of file \fBglad\&.c\fP\&.
.SS "PFNGLTEXCOORDP1UIPROC glad_glTexCoordP1ui = NULL"

.PP
Definition at line \fB509\fP of file \fBglad\&.c\fP\&.
.SS "PFNGLTEXCOORDP1UIVPROC glad_glTexCoordP1uiv = NULL"

.PP
Definition at line \fB510\fP of file \fBglad\&.c\fP\&.
.SS "PFNGLTEXCOORDP2UIPROC glad_glTexCoordP2ui = NULL"

.PP
Definition at line \fB511\fP of file \fBglad\&.c\fP\&.
.SS "PFNGLTEXCOORDP2UIVPROC glad_glTexCoordP2uiv = NULL"

.PP
Definition at line \fB512\fP of file \fBglad\&.c\fP\&.
.SS "PFNGLTEXCOORDP3UIPROC glad_glTexCoordP3ui = NULL"

.PP
Definition at line \fB513\fP of file \fBglad\&.c\fP\&.
.SS "PFNGLTEXCOORDP3UIVPROC glad_glTexCoordP3uiv = NULL"

.PP
Definition at line \fB514\fP of file \fBglad\&.c\fP\&.
.SS "PFNGLTEXCOORDP4UIPROC glad_glTexCoordP4ui = NULL"

.PP
Definition at line \fB515\fP of file \fBglad\&.c\fP\&.
.SS "PFNGLTEXCOORDP4UIVPROC glad_glTexCoordP4uiv = NULL"

.PP
Definition at line \fB516\fP of file \fBglad\&.c\fP\&.
.SS "PFNGLTEXIMAGE1DPROC glad_glTexImage1D = NULL"

.PP
Definition at line \fB517\fP of file \fBglad\&.c\fP\&.
.SS "PFNGLTEXIMAGE2DPROC glad_glTexImage2D = NULL"

.PP
Definition at line \fB518\fP of file \fBglad\&.c\fP\&.
.SS "PFNGLTEXIMAGE2DMULTISAMPLEPROC glad_glTexImage2DMultisample = NULL"

.PP
Definition at line \fB519\fP of file \fBglad\&.c\fP\&.
.SS "PFNGLTEXIMAGE3DPROC glad_glTexImage3D = NULL"

.PP
Definition at line \fB520\fP of file \fBglad\&.c\fP\&.
.SS "PFNGLTEXIMAGE3DMULTISAMPLEPROC glad_glTexImage3DMultisample = NULL"

.PP
Definition at line \fB521\fP of file \fBglad\&.c\fP\&.
.SS "PFNGLTEXPARAMETERFPROC glad_glTexParameterf = NULL"

.PP
Definition at line \fB524\fP of file \fBglad\&.c\fP\&.
.SS "PFNGLTEXPARAMETERFVPROC glad_glTexParameterfv = NULL"

.PP
Definition at line \fB525\fP of file \fBglad\&.c\fP\&.
.SS "PFNGLTEXPARAMETERIPROC glad_glTexParameteri = NULL"

.PP
Definition at line \fB526\fP of file \fBglad\&.c\fP\&.
.SS "PFNGLTEXPARAMETERIIVPROC glad_glTexParameterIiv = NULL"

.PP
Definition at line \fB522\fP of file \fBglad\&.c\fP\&.
.SS "PFNGLTEXPARAMETERIUIVPROC glad_glTexParameterIuiv = NULL"

.PP
Definition at line \fB523\fP of file \fBglad\&.c\fP\&.
.SS "PFNGLTEXPARAMETERIVPROC glad_glTexParameteriv = NULL"

.PP
Definition at line \fB527\fP of file \fBglad\&.c\fP\&.
.SS "PFNGLTEXSUBIMAGE1DPROC glad_glTexSubImage1D = NULL"

.PP
Definition at line \fB528\fP of file \fBglad\&.c\fP\&.
.SS "PFNGLTEXSUBIMAGE2DPROC glad_glTexSubImage2D = NULL"

.PP
Definition at line \fB529\fP of file \fBglad\&.c\fP\&.
.SS "PFNGLTEXSUBIMAGE3DPROC glad_glTexSubImage3D = NULL"

.PP
Definition at line \fB530\fP of file \fBglad\&.c\fP\&.
.SS "PFNGLTRANSFORMFEEDBACKVARYINGSPROC glad_glTransformFeedbackVaryings = NULL"

.PP
Definition at line \fB531\fP of file \fBglad\&.c\fP\&.
.SS "PFNGLUNIFORM1FPROC glad_glUniform1f = NULL"

.PP
Definition at line \fB532\fP of file \fBglad\&.c\fP\&.
.SS "PFNGLUNIFORM1FVPROC glad_glUniform1fv = NULL"

.PP
Definition at line \fB533\fP of file \fBglad\&.c\fP\&.
.SS "PFNGLUNIFORM1IPROC glad_glUniform1i = NULL"

.PP
Definition at line \fB534\fP of file \fBglad\&.c\fP\&.
.SS "PFNGLUNIFORM1IVPROC glad_glUniform1iv = NULL"

.PP
Definition at line \fB535\fP of file \fBglad\&.c\fP\&.
.SS "PFNGLUNIFORM1UIPROC glad_glUniform1ui = NULL"

.PP
Definition at line \fB536\fP of file \fBglad\&.c\fP\&.
.SS "PFNGLUNIFORM1UIVPROC glad_glUniform1uiv = NULL"

.PP
Definition at line \fB537\fP of file \fBglad\&.c\fP\&.
.SS "PFNGLUNIFORM2FPROC glad_glUniform2f = NULL"

.PP
Definition at line \fB538\fP of file \fBglad\&.c\fP\&.
.SS "PFNGLUNIFORM2FVPROC glad_glUniform2fv = NULL"

.PP
Definition at line \fB539\fP of file \fBglad\&.c\fP\&.
.SS "PFNGLUNIFORM2IPROC glad_glUniform2i = NULL"

.PP
Definition at line \fB540\fP of file \fBglad\&.c\fP\&.
.SS "PFNGLUNIFORM2IVPROC glad_glUniform2iv = NULL"

.PP
Definition at line \fB541\fP of file \fBglad\&.c\fP\&.
.SS "PFNGLUNIFORM2UIPROC glad_glUniform2ui = NULL"

.PP
Definition at line \fB542\fP of file \fBglad\&.c\fP\&.
.SS "PFNGLUNIFORM2UIVPROC glad_glUniform2uiv = NULL"

.PP
Definition at line \fB543\fP of file \fBglad\&.c\fP\&.
.SS "PFNGLUNIFORM3FPROC glad_glUniform3f = NULL"

.PP
Definition at line \fB544\fP of file \fBglad\&.c\fP\&.
.SS "PFNGLUNIFORM3FVPROC glad_glUniform3fv = NULL"

.PP
Definition at line \fB545\fP of file \fBglad\&.c\fP\&.
.SS "PFNGLUNIFORM3IPROC glad_glUniform3i = NULL"

.PP
Definition at line \fB546\fP of file \fBglad\&.c\fP\&.
.SS "PFNGLUNIFORM3IVPROC glad_glUniform3iv = NULL"

.PP
Definition at line \fB547\fP of file \fBglad\&.c\fP\&.
.SS "PFNGLUNIFORM3UIPROC glad_glUniform3ui = NULL"

.PP
Definition at line \fB548\fP of file \fBglad\&.c\fP\&.
.SS "PFNGLUNIFORM3UIVPROC glad_glUniform3uiv = NULL"

.PP
Definition at line \fB549\fP of file \fBglad\&.c\fP\&.
.SS "PFNGLUNIFORM4FPROC glad_glUniform4f = NULL"

.PP
Definition at line \fB550\fP of file \fBglad\&.c\fP\&.
.SS "PFNGLUNIFORM4FVPROC glad_glUniform4fv = NULL"

.PP
Definition at line \fB551\fP of file \fBglad\&.c\fP\&.
.SS "PFNGLUNIFORM4IPROC glad_glUniform4i = NULL"

.PP
Definition at line \fB552\fP of file \fBglad\&.c\fP\&.
.SS "PFNGLUNIFORM4IVPROC glad_glUniform4iv = NULL"

.PP
Definition at line \fB553\fP of file \fBglad\&.c\fP\&.
.SS "PFNGLUNIFORM4UIPROC glad_glUniform4ui = NULL"

.PP
Definition at line \fB554\fP of file \fBglad\&.c\fP\&.
.SS "PFNGLUNIFORM4UIVPROC glad_glUniform4uiv = NULL"

.PP
Definition at line \fB555\fP of file \fBglad\&.c\fP\&.
.SS "PFNGLUNIFORMBLOCKBINDINGPROC glad_glUniformBlockBinding = NULL"

.PP
Definition at line \fB556\fP of file \fBglad\&.c\fP\&.
.SS "PFNGLUNIFORMMATRIX2FVPROC glad_glUniformMatrix2fv = NULL"

.PP
Definition at line \fB557\fP of file \fBglad\&.c\fP\&.
.SS "PFNGLUNIFORMMATRIX2X3FVPROC glad_glUniformMatrix2x3fv = NULL"

.PP
Definition at line \fB558\fP of file \fBglad\&.c\fP\&.
.SS "PFNGLUNIFORMMATRIX2X4FVPROC glad_glUniformMatrix2x4fv = NULL"

.PP
Definition at line \fB559\fP of file \fBglad\&.c\fP\&.
.SS "PFNGLUNIFORMMATRIX3FVPROC glad_glUniformMatrix3fv = NULL"

.PP
Definition at line \fB560\fP of file \fBglad\&.c\fP\&.
.SS "PFNGLUNIFORMMATRIX3X2FVPROC glad_glUniformMatrix3x2fv = NULL"

.PP
Definition at line \fB561\fP of file \fBglad\&.c\fP\&.
.SS "PFNGLUNIFORMMATRIX3X4FVPROC glad_glUniformMatrix3x4fv = NULL"

.PP
Definition at line \fB562\fP of file \fBglad\&.c\fP\&.
.SS "PFNGLUNIFORMMATRIX4FVPROC glad_glUniformMatrix4fv = NULL"

.PP
Definition at line \fB563\fP of file \fBglad\&.c\fP\&.
.SS "PFNGLUNIFORMMATRIX4X2FVPROC glad_glUniformMatrix4x2fv = NULL"

.PP
Definition at line \fB564\fP of file \fBglad\&.c\fP\&.
.SS "PFNGLUNIFORMMATRIX4X3FVPROC glad_glUniformMatrix4x3fv = NULL"

.PP
Definition at line \fB565\fP of file \fBglad\&.c\fP\&.
.SS "PFNGLUNMAPBUFFERPROC glad_glUnmapBuffer = NULL"

.PP
Definition at line \fB566\fP of file \fBglad\&.c\fP\&.
.SS "PFNGLUSEPROGRAMPROC glad_glUseProgram = NULL"

.PP
Definition at line \fB567\fP of file \fBglad\&.c\fP\&.
.SS "PFNGLVALIDATEPROGRAMPROC glad_glValidateProgram = NULL"

.PP
Definition at line \fB568\fP of file \fBglad\&.c\fP\&.
.SS "PFNGLVERTEXATTRIB1DPROC glad_glVertexAttrib1d = NULL"

.PP
Definition at line \fB569\fP of file \fBglad\&.c\fP\&.
.SS "PFNGLVERTEXATTRIB1DVPROC glad_glVertexAttrib1dv = NULL"

.PP
Definition at line \fB570\fP of file \fBglad\&.c\fP\&.
.SS "PFNGLVERTEXATTRIB1FPROC glad_glVertexAttrib1f = NULL"

.PP
Definition at line \fB571\fP of file \fBglad\&.c\fP\&.
.SS "PFNGLVERTEXATTRIB1FVPROC glad_glVertexAttrib1fv = NULL"

.PP
Definition at line \fB572\fP of file \fBglad\&.c\fP\&.
.SS "PFNGLVERTEXATTRIB1SPROC glad_glVertexAttrib1s = NULL"

.PP
Definition at line \fB573\fP of file \fBglad\&.c\fP\&.
.SS "PFNGLVERTEXATTRIB1SVPROC glad_glVertexAttrib1sv = NULL"

.PP
Definition at line \fB574\fP of file \fBglad\&.c\fP\&.
.SS "PFNGLVERTEXATTRIB2DPROC glad_glVertexAttrib2d = NULL"

.PP
Definition at line \fB575\fP of file \fBglad\&.c\fP\&.
.SS "PFNGLVERTEXATTRIB2DVPROC glad_glVertexAttrib2dv = NULL"

.PP
Definition at line \fB576\fP of file \fBglad\&.c\fP\&.
.SS "PFNGLVERTEXATTRIB2FPROC glad_glVertexAttrib2f = NULL"

.PP
Definition at line \fB577\fP of file \fBglad\&.c\fP\&.
.SS "PFNGLVERTEXATTRIB2FVPROC glad_glVertexAttrib2fv = NULL"

.PP
Definition at line \fB578\fP of file \fBglad\&.c\fP\&.
.SS "PFNGLVERTEXATTRIB2SPROC glad_glVertexAttrib2s = NULL"

.PP
Definition at line \fB579\fP of file \fBglad\&.c\fP\&.
.SS "PFNGLVERTEXATTRIB2SVPROC glad_glVertexAttrib2sv = NULL"

.PP
Definition at line \fB580\fP of file \fBglad\&.c\fP\&.
.SS "PFNGLVERTEXATTRIB3DPROC glad_glVertexAttrib3d = NULL"

.PP
Definition at line \fB581\fP of file \fBglad\&.c\fP\&.
.SS "PFNGLVERTEXATTRIB3DVPROC glad_glVertexAttrib3dv = NULL"

.PP
Definition at line \fB582\fP of file \fBglad\&.c\fP\&.
.SS "PFNGLVERTEXATTRIB3FPROC glad_glVertexAttrib3f = NULL"

.PP
Definition at line \fB583\fP of file \fBglad\&.c\fP\&.
.SS "PFNGLVERTEXATTRIB3FVPROC glad_glVertexAttrib3fv = NULL"

.PP
Definition at line \fB584\fP of file \fBglad\&.c\fP\&.
.SS "PFNGLVERTEXATTRIB3SPROC glad_glVertexAttrib3s = NULL"

.PP
Definition at line \fB585\fP of file \fBglad\&.c\fP\&.
.SS "PFNGLVERTEXATTRIB3SVPROC glad_glVertexAttrib3sv = NULL"

.PP
Definition at line \fB586\fP of file \fBglad\&.c\fP\&.
.SS "PFNGLVERTEXATTRIB4BVPROC glad_glVertexAttrib4bv = NULL"

.PP
Definition at line \fB594\fP of file \fBglad\&.c\fP\&.
.SS "PFNGLVERTEXATTRIB4DPROC glad_glVertexAttrib4d = NULL"

.PP
Definition at line \fB595\fP of file \fBglad\&.c\fP\&.
.SS "PFNGLVERTEXATTRIB4DVPROC glad_glVertexAttrib4dv = NULL"

.PP
Definition at line \fB596\fP of file \fBglad\&.c\fP\&.
.SS "PFNGLVERTEXATTRIB4FPROC glad_glVertexAttrib4f = NULL"

.PP
Definition at line \fB597\fP of file \fBglad\&.c\fP\&.
.SS "PFNGLVERTEXATTRIB4FVPROC glad_glVertexAttrib4fv = NULL"

.PP
Definition at line \fB598\fP of file \fBglad\&.c\fP\&.
.SS "PFNGLVERTEXATTRIB4IVPROC glad_glVertexAttrib4iv = NULL"

.PP
Definition at line \fB599\fP of file \fBglad\&.c\fP\&.
.SS "PFNGLVERTEXATTRIB4NBVPROC glad_glVertexAttrib4Nbv = NULL"

.PP
Definition at line \fB587\fP of file \fBglad\&.c\fP\&.
.SS "PFNGLVERTEXATTRIB4NIVPROC glad_glVertexAttrib4Niv = NULL"

.PP
Definition at line \fB588\fP of file \fBglad\&.c\fP\&.
.SS "PFNGLVERTEXATTRIB4NSVPROC glad_glVertexAttrib4Nsv = NULL"

.PP
Definition at line \fB589\fP of file \fBglad\&.c\fP\&.
.SS "PFNGLVERTEXATTRIB4NUBPROC glad_glVertexAttrib4Nub = NULL"

.PP
Definition at line \fB590\fP of file \fBglad\&.c\fP\&.
.SS "PFNGLVERTEXATTRIB4NUBVPROC glad_glVertexAttrib4Nubv = NULL"

.PP
Definition at line \fB591\fP of file \fBglad\&.c\fP\&.
.SS "PFNGLVERTEXATTRIB4NUIVPROC glad_glVertexAttrib4Nuiv = NULL"

.PP
Definition at line \fB592\fP of file \fBglad\&.c\fP\&.
.SS "PFNGLVERTEXATTRIB4NUSVPROC glad_glVertexAttrib4Nusv = NULL"

.PP
Definition at line \fB593\fP of file \fBglad\&.c\fP\&.
.SS "PFNGLVERTEXATTRIB4SPROC glad_glVertexAttrib4s = NULL"

.PP
Definition at line \fB600\fP of file \fBglad\&.c\fP\&.
.SS "PFNGLVERTEXATTRIB4SVPROC glad_glVertexAttrib4sv = NULL"

.PP
Definition at line \fB601\fP of file \fBglad\&.c\fP\&.
.SS "PFNGLVERTEXATTRIB4UBVPROC glad_glVertexAttrib4ubv = NULL"

.PP
Definition at line \fB602\fP of file \fBglad\&.c\fP\&.
.SS "PFNGLVERTEXATTRIB4UIVPROC glad_glVertexAttrib4uiv = NULL"

.PP
Definition at line \fB603\fP of file \fBglad\&.c\fP\&.
.SS "PFNGLVERTEXATTRIB4USVPROC glad_glVertexAttrib4usv = NULL"

.PP
Definition at line \fB604\fP of file \fBglad\&.c\fP\&.
.SS "PFNGLVERTEXATTRIBDIVISORPROC glad_glVertexAttribDivisor = NULL"

.PP
Definition at line \fB605\fP of file \fBglad\&.c\fP\&.
.SS "PFNGLVERTEXATTRIBI1IPROC glad_glVertexAttribI1i = NULL"

.PP
Definition at line \fB606\fP of file \fBglad\&.c\fP\&.
.SS "PFNGLVERTEXATTRIBI1IVPROC glad_glVertexAttribI1iv = NULL"

.PP
Definition at line \fB607\fP of file \fBglad\&.c\fP\&.
.SS "PFNGLVERTEXATTRIBI1UIPROC glad_glVertexAttribI1ui = NULL"

.PP
Definition at line \fB608\fP of file \fBglad\&.c\fP\&.
.SS "PFNGLVERTEXATTRIBI1UIVPROC glad_glVertexAttribI1uiv = NULL"

.PP
Definition at line \fB609\fP of file \fBglad\&.c\fP\&.
.SS "PFNGLVERTEXATTRIBI2IPROC glad_glVertexAttribI2i = NULL"

.PP
Definition at line \fB610\fP of file \fBglad\&.c\fP\&.
.SS "PFNGLVERTEXATTRIBI2IVPROC glad_glVertexAttribI2iv = NULL"

.PP
Definition at line \fB611\fP of file \fBglad\&.c\fP\&.
.SS "PFNGLVERTEXATTRIBI2UIPROC glad_glVertexAttribI2ui = NULL"

.PP
Definition at line \fB612\fP of file \fBglad\&.c\fP\&.
.SS "PFNGLVERTEXATTRIBI2UIVPROC glad_glVertexAttribI2uiv = NULL"

.PP
Definition at line \fB613\fP of file \fBglad\&.c\fP\&.
.SS "PFNGLVERTEXATTRIBI3IPROC glad_glVertexAttribI3i = NULL"

.PP
Definition at line \fB614\fP of file \fBglad\&.c\fP\&.
.SS "PFNGLVERTEXATTRIBI3IVPROC glad_glVertexAttribI3iv = NULL"

.PP
Definition at line \fB615\fP of file \fBglad\&.c\fP\&.
.SS "PFNGLVERTEXATTRIBI3UIPROC glad_glVertexAttribI3ui = NULL"

.PP
Definition at line \fB616\fP of file \fBglad\&.c\fP\&.
.SS "PFNGLVERTEXATTRIBI3UIVPROC glad_glVertexAttribI3uiv = NULL"

.PP
Definition at line \fB617\fP of file \fBglad\&.c\fP\&.
.SS "PFNGLVERTEXATTRIBI4BVPROC glad_glVertexAttribI4bv = NULL"

.PP
Definition at line \fB618\fP of file \fBglad\&.c\fP\&.
.SS "PFNGLVERTEXATTRIBI4IPROC glad_glVertexAttribI4i = NULL"

.PP
Definition at line \fB619\fP of file \fBglad\&.c\fP\&.
.SS "PFNGLVERTEXATTRIBI4IVPROC glad_glVertexAttribI4iv = NULL"

.PP
Definition at line \fB620\fP of file \fBglad\&.c\fP\&.
.SS "PFNGLVERTEXATTRIBI4SVPROC glad_glVertexAttribI4sv = NULL"

.PP
Definition at line \fB621\fP of file \fBglad\&.c\fP\&.
.SS "PFNGLVERTEXATTRIBI4UBVPROC glad_glVertexAttribI4ubv = NULL"

.PP
Definition at line \fB622\fP of file \fBglad\&.c\fP\&.
.SS "PFNGLVERTEXATTRIBI4UIPROC glad_glVertexAttribI4ui = NULL"

.PP
Definition at line \fB623\fP of file \fBglad\&.c\fP\&.
.SS "PFNGLVERTEXATTRIBI4UIVPROC glad_glVertexAttribI4uiv = NULL"

.PP
Definition at line \fB624\fP of file \fBglad\&.c\fP\&.
.SS "PFNGLVERTEXATTRIBI4USVPROC glad_glVertexAttribI4usv = NULL"

.PP
Definition at line \fB625\fP of file \fBglad\&.c\fP\&.
.SS "PFNGLVERTEXATTRIBIPOINTERPROC glad_glVertexAttribIPointer = NULL"

.PP
Definition at line \fB626\fP of file \fBglad\&.c\fP\&.
.SS "PFNGLVERTEXATTRIBP1UIPROC glad_glVertexAttribP1ui = NULL"

.PP
Definition at line \fB627\fP of file \fBglad\&.c\fP\&.
.SS "PFNGLVERTEXATTRIBP1UIVPROC glad_glVertexAttribP1uiv = NULL"

.PP
Definition at line \fB628\fP of file \fBglad\&.c\fP\&.
.SS "PFNGLVERTEXATTRIBP2UIPROC glad_glVertexAttribP2ui = NULL"

.PP
Definition at line \fB629\fP of file \fBglad\&.c\fP\&.
.SS "PFNGLVERTEXATTRIBP2UIVPROC glad_glVertexAttribP2uiv = NULL"

.PP
Definition at line \fB630\fP of file \fBglad\&.c\fP\&.
.SS "PFNGLVERTEXATTRIBP3UIPROC glad_glVertexAttribP3ui = NULL"

.PP
Definition at line \fB631\fP of file \fBglad\&.c\fP\&.
.SS "PFNGLVERTEXATTRIBP3UIVPROC glad_glVertexAttribP3uiv = NULL"

.PP
Definition at line \fB632\fP of file \fBglad\&.c\fP\&.
.SS "PFNGLVERTEXATTRIBP4UIPROC glad_glVertexAttribP4ui = NULL"

.PP
Definition at line \fB633\fP of file \fBglad\&.c\fP\&.
.SS "PFNGLVERTEXATTRIBP4UIVPROC glad_glVertexAttribP4uiv = NULL"

.PP
Definition at line \fB634\fP of file \fBglad\&.c\fP\&.
.SS "PFNGLVERTEXATTRIBPOINTERPROC glad_glVertexAttribPointer = NULL"

.PP
Definition at line \fB635\fP of file \fBglad\&.c\fP\&.
.SS "PFNGLVERTEXP2UIPROC glad_glVertexP2ui = NULL"

.PP
Definition at line \fB636\fP of file \fBglad\&.c\fP\&.
.SS "PFNGLVERTEXP2UIVPROC glad_glVertexP2uiv = NULL"

.PP
Definition at line \fB637\fP of file \fBglad\&.c\fP\&.
.SS "PFNGLVERTEXP3UIPROC glad_glVertexP3ui = NULL"

.PP
Definition at line \fB638\fP of file \fBglad\&.c\fP\&.
.SS "PFNGLVERTEXP3UIVPROC glad_glVertexP3uiv = NULL"

.PP
Definition at line \fB639\fP of file \fBglad\&.c\fP\&.
.SS "PFNGLVERTEXP4UIPROC glad_glVertexP4ui = NULL"

.PP
Definition at line \fB640\fP of file \fBglad\&.c\fP\&.
.SS "PFNGLVERTEXP4UIVPROC glad_glVertexP4uiv = NULL"

.PP
Definition at line \fB641\fP of file \fBglad\&.c\fP\&.
.SS "PFNGLVIEWPORTPROC glad_glViewport = NULL"

.PP
Definition at line \fB642\fP of file \fBglad\&.c\fP\&.
.SS "PFNGLWAITSYNCPROC glad_glWaitSync = NULL"

.PP
Definition at line \fB643\fP of file \fBglad\&.c\fP\&.
.SS "struct gladGLversionStruct GLVersion = { 0, 0 }"

.PP
Definition at line \fB159\fP of file \fBglad\&.c\fP\&.
.SH "Author"
.PP 
Generated automatically by Doxygen for Engine from the source code\&.
