CC=gcc
STD=-std=c99
PFLAGS=-I SpaceGame/include -I SpaceGame/include/engine \
-I SpaceGame/include/engine/entity -I SpaceGame/include/engine/opengl \
-I SpaceGame/include/engine/utility
SRCDIRS=SpaceGame/src SpaceGame/src/engine SpaceGame/src/engine/entity \
SpaceGame/src/engine/glad SpaceGame/src/engine/opengl SpaceGame/src/engine/utility
LDFLAGS=-lglfw3 