PROJECT_DIR?=/home/shyguy/Desktop/SpaceGame
LIBRARY_DIR?=$(PROJECT_DIR)/lib
BUILD_DIR?=$(PROJECT_DIR)/build

LIB_CGLM_DIR?=$(LIBRARY_DIR)/cglm
LIB_CGLM_INC_DIR?=$(LIB_CGLM_DIR)/include

LIB_GLAD_DIR?=$(LIBRARY_DIR)/glad
LIB_GLAD_INC_DIR?=$(LIB_GLAD_DIR)/include

LIB_GLFW_DIR?=$(LIBRARY_DIR)/glfw
LIB_GLFW_INC_DIR?=$(LIB_GLFW_DIR)/include

LIB_OBSIDIAN_DIR?=$(LIBRARY_DIR)/obsidian
LIB_OBSIDIAN_INC_DIR?=$(LIB_OBSIDIAN_DIR)/include

LIB_STBIMAGE_DIR?=$(LIBRARY_DIR)/stb-image
LIB_STBIMAGE_INC_DIR?=$(LIB_STBIMAGE_DIR)/include


OBMDLCVTR_DIR?=$(PROJECT_DIR)/obmdlcvtr
OBMDLCVTR_INC_DIR?=$(OBMDLCVTR_DIR)/include
OBMDLCVTR_SRC_DIR?=$(OBMDLCVTR_DIR)/src

OBSIDIAN_DIR?=$(PROJECT_DIR)/obsidian
OBSIDIAN_INC_DIR?=$(OBSIDIAN_DIR)/include
OBSIDIAN_SRC_DIR?=$(OBSIDIAN_DIR)/src

OBTEXCVTR_DIR?=$(PROJECT_DIR)/obtexcvtr
OBTEXCVTR_INC_DIR?=$(OBTEXCVTR_DIR)/include
OBTEXCVTR_SRC_DIR?=$(OBTEXCVTR_DIR)/src

CELESTIAL_DIR?=$(PROJECT_DIR)/space-game
CELESTIAL_INC_DIR?=$(CELESTIAL_DIR)/include
CELESTIAL_SRC_DIR?=$(CELESTIAL_DIR)/src