.TH "SpaceGame/engine_component_funcs.c" 3 "Version 0.1.0" "Engine" \" -*- nroff -*-
.ad l
.nh
.SH NAME
SpaceGame/engine_component_funcs.c
.SH SYNOPSIS
.br
.PP
\fR#include 'engine_defs\&.h'\fP
.br
\fR#include 'engine_components\&.h'\fP
.br
\fR#include 'engine_renderer\&.h'\fP
.br
\fR#include <stdio\&.h>\fP
.br

.SS "Functions"

.in +1c
.ti -1c
.RI "void \fB__engine__defaultRendererComponentFunc\fP (\fBEngineEntity\fP *ent, \fBEngineContext\fP *ctx, float deltaTime)"
.br
.ti -1c
.RI "void \fB__engine__defaultControllerComponentFunc\fP (\fBEngineEntity\fP *ent, \fBEngineContext\fP *ctx, float deltaTime)"
.br
.ti -1c
.RI "void \fB__engine__defaultTickComponentFunc\fP (\fBEngineEntity\fP *ent, \fBEngineContext\fP *ctx, float deltaTime)"
.br
.in -1c
.SH "Function Documentation"
.PP 
.SS "void __engine__defaultControllerComponentFunc (\fBEngineEntity\fP * ent, \fBEngineContext\fP * ctx, float deltaTime)"

.PP
Definition at line \fB12\fP of file \fBengine_component_funcs\&.c\fP\&.
.SS "void __engine__defaultRendererComponentFunc (\fBEngineEntity\fP * ent, \fBEngineContext\fP * ctx, float deltaTime)"

.PP
Definition at line \fB7\fP of file \fBengine_component_funcs\&.c\fP\&.
.SS "void __engine__defaultTickComponentFunc (\fBEngineEntity\fP * ent, \fBEngineContext\fP * ctx, float deltaTime)"

.PP
Definition at line \fB28\fP of file \fBengine_component_funcs\&.c\fP\&.
.SH "Author"
.PP 
Generated automatically by Doxygen for Engine from the source code\&.
