.TH "engine_texture_pair" 3 "Version 0.1.0" "Engine" \" -*- nroff -*-
.ad l
.nh
.SH NAME
engine_texture_pair \- Used to make a pseudo-dictionary for the engine\&.  

.SH SYNOPSIS
.br
.PP
.PP
\fR#include <engine_defs\&.h>\fP
.SS "Data Fields"

.in +1c
.ti -1c
.RI "EngineTextureKey \fBkey\fP"
.br
.ti -1c
.RI "EngineTexture * \fBvalue\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Used to make a pseudo-dictionary for the engine\&. 
.PP
Definition at line \fB83\fP of file \fBengine_defs\&.h\fP\&.
.SH "Field Documentation"
.PP 
.SS "EngineTextureKey key"

.PP
Definition at line \fB84\fP of file \fBengine_defs\&.h\fP\&.
.SS "EngineTexture* value"

.PP
Definition at line \fB85\fP of file \fBengine_defs\&.h\fP\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Engine from the source code\&.
