.TH "engine_texture" 3 "Version 0.1.0" "Engine" \" -*- nroff -*-
.ad l
.nh
.SH NAME
engine_texture \- A texture handle that contains all necessary texture information\&.  

.SH SYNOPSIS
.br
.PP
.PP
\fR#include <engine_defs\&.h>\fP
.SS "Data Fields"

.in +1c
.ti -1c
.RI "unsigned int \fBid\fP"
.br
.ti -1c
.RI "unsigned int \fBwidth\fP"
.br
.ti -1c
.RI "unsigned int \fBheight\fP"
.br
.ti -1c
.RI "unsigned int \fBinternalformat\fP"
.br
.ti -1c
.RI "unsigned int \fBimageformat\fP"
.br
.ti -1c
.RI "unsigned int \fBwraps\fP"
.br
.ti -1c
.RI "unsigned int \fBwrapt\fP"
.br
.ti -1c
.RI "unsigned int \fBfiltermax\fP"
.br
.ti -1c
.RI "unsigned int \fBfiltermin\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
A texture handle that contains all necessary texture information\&. 
.PP
Definition at line \fB71\fP of file \fBengine_defs\&.h\fP\&.
.SH "Field Documentation"
.PP 
.SS "unsigned int filtermax"

.PP
Definition at line \fB77\fP of file \fBengine_defs\&.h\fP\&.
.SS "unsigned int filtermin"

.PP
Definition at line \fB77\fP of file \fBengine_defs\&.h\fP\&.
.SS "unsigned int height"

.PP
Definition at line \fB73\fP of file \fBengine_defs\&.h\fP\&.
.SS "unsigned int id"

.PP
Definition at line \fB72\fP of file \fBengine_defs\&.h\fP\&.
.SS "unsigned int imageformat"

.PP
Definition at line \fB75\fP of file \fBengine_defs\&.h\fP\&.
.SS "unsigned int internalformat"

.PP
Definition at line \fB74\fP of file \fBengine_defs\&.h\fP\&.
.SS "unsigned int width"

.PP
Definition at line \fB73\fP of file \fBengine_defs\&.h\fP\&.
.SS "unsigned int wraps"

.PP
Definition at line \fB76\fP of file \fBengine_defs\&.h\fP\&.
.SS "unsigned int wrapt"

.PP
Definition at line \fB76\fP of file \fBengine_defs\&.h\fP\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Engine from the source code\&.
