.TH "SpaceGame/game.c" 3 "Version 0.1.0" "Engine" \" -*- nroff -*-
.ad l
.nh
.SH NAME
SpaceGame/game.c
.SH SYNOPSIS
.br
.PP
\fR#include 'engine\&.h'\fP
.br
\fR#include 'engine_shaders\&.h'\fP
.br
\fR#include 'engine_buffers\&.h'\fP
.br
\fR#include 'engine_textures\&.h'\fP
.br
\fR#include 'engine_entity\&.h'\fP
.br
\fR#include 'engine_renderer\&.h'\fP
.br
\fR#include 'engine_components\&.h'\fP
.br
\fR#include 'engine_utils\&.h'\fP
.br
\fR#include <stdio\&.h>\fP
.br

.SS "Functions"

.in +1c
.ti -1c
.RI "int \fBmain\fP (void)"
.br
.in -1c
.SS "Variables"

.in +1c
.ti -1c
.RI "float \fBvertices\fP []"
.br
.in -1c
.SH "Function Documentation"
.PP 
.SS "int main (void )"

.PP
Definition at line \fB32\fP of file \fBgame\&.c\fP\&.
.SH "Variable Documentation"
.PP 
.SS "float vertices[]"
\fBInitial value:\fP
.nf
               = {
    
    0\&.0f, 1\&.0f,     1\&.0f, 1\&.0f, 1\&.0f,   0\&.0f, 1\&.0f,
    1\&.0f, 0\&.0f,     1\&.0f, 1\&.0f, 1\&.0f,   1\&.0f, 0\&.0f,
    0\&.0f, 0\&.0f,     1\&.0f, 1\&.0f, 1\&.0f,   0\&.0f, 0\&.0f,
    0\&.0f, 1\&.0f,     1\&.0f, 1\&.0f, 1\&.0f,   0\&.0f, 1\&.0f,
    1\&.0f, 1\&.0f,     1\&.0f, 1\&.0f, 1\&.0f,   1\&.0f, 1\&.0f,
    1\&.0f, 0\&.0f,     1\&.0f, 1\&.0f, 1\&.0f,   1\&.0f, 0\&.0f,
}
.PP
.fi

.PP
Definition at line \fB12\fP of file \fBgame\&.c\fP\&.
.SH "Author"
.PP 
Generated automatically by Doxygen for Engine from the source code\&.
