.TH "linklist" 3 "Version 0.1.0" "Engine" \" -*- nroff -*-
.ad l
.nh
.SH NAME
linklist \- A standard link list data structure\&.  

.SH SYNOPSIS
.br
.PP
.PP
\fR#include <engine_defs\&.h>\fP
.SS "Data Fields"

.in +1c
.ti -1c
.RI "char * \fBlista\fP"
.br
.ti -1c
.RI "char * \fBlistb\fP"
.br
.ti -1c
.RI "size_t \fBtypesize\fP"
.br
.ti -1c
.RI "size_t \fBarrsize\fP"
.br
.ti -1c
.RI "EBOOL \fBaalloc\fP"
.br
.ti -1c
.RI "EBOOL \fBballoc\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
A standard link list data structure\&. 
.PP
Definition at line \fB111\fP of file \fBengine_defs\&.h\fP\&.
.SH "Field Documentation"
.PP 
.SS "EBOOL aalloc"

.PP
Definition at line \fB118\fP of file \fBengine_defs\&.h\fP\&.
.SS "size_t arrsize"

.PP
Definition at line \fB116\fP of file \fBengine_defs\&.h\fP\&.
.SS "EBOOL balloc"

.PP
Definition at line \fB119\fP of file \fBengine_defs\&.h\fP\&.
.SS "char* lista"

.PP
Definition at line \fB112\fP of file \fBengine_defs\&.h\fP\&.
.SS "char* listb"

.PP
Definition at line \fB113\fP of file \fBengine_defs\&.h\fP\&.
.SS "size_t typesize"

.PP
Definition at line \fB115\fP of file \fBengine_defs\&.h\fP\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Engine from the source code\&.
