.TH "window_config" 3 "Version 0.1.0" "Engine" \" -*- nroff -*-
.ad l
.nh
.SH NAME
window_config \- The window config tells the engine how to setup the window\&.  

.SH SYNOPSIS
.br
.PP
.PP
\fR#include <engine_defs\&.h>\fP
.SS "Data Fields"

.in +1c
.ti -1c
.RI "char * \fBtitle\fP"
.br
.ti -1c
.RI "unsigned int \fBwidth\fP"
.br
.ti -1c
.RI "unsigned int \fBheight\fP"
.br
.ti -1c
.RI "EBOOL \fBresizable\fP"
.br
.ti -1c
.RI "EBOOL \fBdoublebuffer\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
The window config tells the engine how to setup the window\&. 
.PP
Definition at line \fB62\fP of file \fBengine_defs\&.h\fP\&.
.SH "Field Documentation"
.PP 
.SS "EBOOL doublebuffer"

.PP
Definition at line \fB65\fP of file \fBengine_defs\&.h\fP\&.
.SS "unsigned int height"

.PP
Definition at line \fB64\fP of file \fBengine_defs\&.h\fP\&.
.SS "EBOOL resizable"

.PP
Definition at line \fB65\fP of file \fBengine_defs\&.h\fP\&.
.SS "char* title"

.PP
Definition at line \fB63\fP of file \fBengine_defs\&.h\fP\&.
.SS "unsigned int width"

.PP
Definition at line \fB64\fP of file \fBengine_defs\&.h\fP\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Engine from the source code\&.
