#ifndef GENERATOR_DEFS_H
#define GENERATOR_DEFS_H

// DELME: remove lines 4-
// TODO: replace these with configurable values, configured by the player upon creating a new game.
#define GALAXY_RAND_PULSAR_CHANCE		0.10
#define GALAXY_RAND_NEUTRON_CHANCE		0.02
#define GALAXY_RAND_BHOLE_CHANCE		0.00025
#define GALAXY_RAND_WDWARF_CHANCE		0.0862
#define GALAXY_RAND_GIANT_CHANCE		0.01
#define GALAXY_RAND_SGIANT_CHANCE		0.01

#define GALAXY_PULSAR_MAX				GAME_MAX_STARS * GALAXY_RAND_PULSAR_CHANCE
#define GALAXY_NEUTRON_MAX				GAME_MAX_STARS * GALAXY_RAND_NEUTRON_CHANCE
#define GALAXY_BHOLE_MAX				GAME_MAX_STARS * GALAXY_RAND_BHOLE_CHANCE
#define GALAXY_WDWARF_MAX				GAME_MAX_STARS * GALAXY_RAND_WDWARF_CHANCE
#define GALAXY_GIANT_MAX				GAME_MAX_STARS * GALAXY_RAND_GIANT_CHANCE
#define GALAXY_SGIANT_MAX				GAME_MAX_STARS * GALAXY_RAND_SGIANT_CHANCE

#define GALAXY_GIANT_MASS_MIN			1.0
#define GALAXY_GIANT_MASS_MAX			20.0
#define GALAXY_PULNEU_MASS_MIN			1.4
#define GALAXY_PULNEU_MASS_MAX			2.1
#define GALAXY_WDWARF_MIN_MASS			0.5
#define GALAXY_WDWARF_MAX_MASS			1.44
#define GALAXY_BHOLE_MIN_MASS			3
#define GALAXY_BHOLE_MAX_MASS			20
#define GALAXY_QUASAR_MIN_MASS			21
#define GALAXY_QUASAR_MAX_MASS			1000

#define GALAXY_BHOLE_DIAMETER_SCALE		6

#define STAR_RAND_MASS_BIAS				0.25
#define STAR_LUMINOSITY_POWER			3.5
#define STAR_DIAMETER_POWER				0.74
#define STAR_SURFACE_POWER				0.505
#define STAR_LIFETIME_POWER				-2.5
#define STAR_HABITABLE_INNER_COEFF		0.95
#define STAR_HABITABLE_OUTER_COEFF		1.37

#endif // GENERATOR_DEFS_H
